### ISSUE TITLE
Is it safe to download

### ISSUE THREAD

**Issue by zestyducks110** [nxengine/nxengine-evo#101]

**Comment by zestyducks110** [comment]
this is stupid, but i am concerned about these things, so i just wanted to kniw

**Comment by isage** [comment]
Obviously, if you're asking such thing, then you don't trust me, so, you wouldn't trust any answer from me. And as i'm the one providing compiled builds, no one else knows how exactly i've built them except me (well, windows versions are automatically built by appveyor but whatever), so no one, except me, can really answer that question.

And that makes this question pointless.

So, read the code, build it yourself.
