### ISSUE TITLE
Sue make no damage in core/misery/sue boss battle

### ISSUE THREAD

**Issue by B4rabbas** [nxengine/nxengine-evo#102]
Sue's attacks don't make any damage during this fight. Neither touching her.

**Comment by isage** [comment]
Her attack (there's only one, spinning) does deal damage (4). Her dash doesn't (and shouldn't), as is touching her.

**Comment by B4rabbas** [comment]
You're sure I've made a run 2 day ago and no damage (witheout dodging but blast her contantly). My bad, in my memorie she was inflaging damages when she touching quote.
