### ISSUE TITLE
Sue disapear escaping before rocks fall

### ISSUE THREAD

**Issue by B4rabbas** [nxengine/nxengine-evo#103]
After sue advertising quote to run for his life, she run to the left few step and disapear.

**Comment by B4rabbas** [comment]
Same glitch just after killing zombie core

**Comment by isage** [comment]
Yeah.
That's not a glitch per se, game script waits for exact amount of time and then just deletes Sue object.
Original game doesn't support widescreen, so the timer tuned for that.

**Comment by isage** [comment]
I wonder how they did it on switch...

**Comment by B4rabbas** [comment]
Is this any chance to improve this in future ?

**Comment by isage** [comment]
What else is there to improve?

**Comment by B4rabbas** [comment]
I mean to change the timer.

**Comment by isage** [comment]
See the relevant commit. It's not an issue anymore. It's not a best fix,
but better than changing timer in scripts in all localisations
