### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by timsueberkrueb** [nxengine/nxengine-evo#115]
Hey, first of all thanks a lot for NxEngine Evo and therefore keeping this gem alive.

I just wanted to let you know that I have created a snap package for NxEngine Evo. If you are interested in taking over maintenance for it, I'd be more than happy to create a pull request for the snapcraft configuration. The build can be easily automated using [build.snapcraft.io](https://snapcraft.io/build). I'm happy to assist with any snap-related issues that may come up.
If you don't want to take over maintenance, I will continue to maintain the package.

While upstream-maintained packages are obviously preferable from a user-perspective, I want to emphasize that this is not an attempt to try handing off the burden of maintaining yet another package format to you if you don't want to or don't have the time for it :) If you do - that'd be awesome of course!

In any case, I think it's time to let you know, now that the snap packaging is reasonably mature and the snap has recently been released to the stable channel (v2.6.4 in beta though since I didn't have enough time yet to properly test it).

* [Packaging Source](https://github.com/timsueberkrueb/cavestory-snap)
* [Store page](https://snapcraft.io/cavestory)

**Comment by isage** [comment]
Why not both?
I can grant you commit access to the repository.
(btw. you are using old version of translations)

**Comment by timsueberkrueb** [comment]
>  (btw. you are using old version of translations)
Oh, right, thanks, will fix!

> I can grant you commit access to the repository.
I think that's not necessary. I can contribute via pull requests :) Great, I will send a PR soon, then.
