### ISSUE TITLE
PS Vita C2-12828-1 Crash 

### ISSUE THREAD

**Issue by sammicol** [nxengine/nxengine-evo#118]
Hi,
I keep getting the C2-12828-1 Saved Core File Succeeded error roughly halfway through the Core boss fight on PS Vita. Everything else has worked great up until this point though.
![2019-04-26-011346](https://user-images.githubusercontent.com/17172835/56785000-4e35ab80-67c1-11e9-8cfd-7c09cb314e66.png)

**Comment by isage** [comment]
That's probably out-of-memory. I'll take a look.

**Comment by isage** [comment]
I've uploaded updated version to releases. That should fix this crash.

**Comment by sammicol** [comment]
Yep it worked!. Thank you.

**Comment by t33st33r** [comment]
Almost same text here:
"ux0:data/psp2core-1576030877-0x000f9435e9-eboot.bin.psp2dmp" is the different part
Attached (GZ compressed)
It is a binary file so I tried to see it using ____ and this is what i could read:
Exception	Data abort exception
Thread ID	0x40010003
Thread name	NXEV00001
EPC	/nx + 0x001132EA
Cause	0x00030004
BadVAddr	0x00000008
a1: 0x00000120	a2: 0x00000000	a3: 0x81C3B830	a4: 0x3F000000
v1: 0x00000000	v2: 0x8140F760	v3: 0x81C3B830	v4: 0x81771D80
v5: 0x8151DF50	v6: 0x000000B6	v7: 0x000000AC	v8: 0x00000000
ip: 0xE007DD9C	sp: 0x814C08F0	lr: 0x811482B3	pc: 0x811482EA
[psp2core-1576030877-0x000f9435e9-eboot.bin.psp2dmp.gz](https://github.com/nxengine/nxengine-evo/files/3948179/psp2core-1576030877-0x000f9435e9-eboot.bin.psp2dmp.gz)
[psp2core-1576030877-0x000f9435e9-eboot.bin.psp2dmp.gz](https://github.com/nxengine/nxengine-evo/files/3948180/psp2core-1576030877-0x000f9435e9-eboot.bin.psp2dmp.gz)
