### ISSUE TITLE
Automated snap builds using build.snapcraft.io

### ISSUE THREAD

**Issue by timsueberkrueb** [nxengine/nxengine-evo#119]
It would be awesome if we could enable [build.snapcraft.io](https://build.snapcraft.io) for automatically building the snap package.

If I understand it correctly, there are basically two options:

1. I would transfer ownership of the snap package to you, so that you can setup build.snapcraft.io (you could add me as a collaborator so I could manage releases if you like).
Unfortunately, due to https://github.com/canonical-web-and-design/build.snapcraft.io/issues/799 it is not possible for me to enable build.snapcraft.io for this repository if you'd grant me access to it.

2. You grant me access to the repository and I hook it up on build.snapcraft.io. If I understand it correctly, this should not be affected by the bug above since I'm already publishing this snap.

Some advantages of using build.snapcraft.io are:
* automated builds and releases to the edge channel
* automated rebuilds when dependencies change
* automated builds for different architectures

**Comment by isage** [comment]
I've granted you admin access rights to this repo.

**Comment by timsueberkrueb** [comment]
Thank you. Unfortunately, it looks like I'd need organization access in order to be able to add the repository to build.snapcraft.io.

**Comment by timsueberkrueb** [comment]
Great, [first build started](https://build.snapcraft.io/user/nxengine/nxengine-evo). Thanks a lot!
