### ISSUE TITLE
what happens if we increase resolution but not scale?

### ISSUE THREAD

**Issue by billywade** [nxengine/nxengine-evo#126]
I was wondering if we'd get just more of the given area and the stage being shrunk down, which might look nice.

**Comment by isage** [comment]
Yes, but that would break some scripts, e.g. some npcs are supposed to
disappear when going offscreen. Some AI logic is disabled for offscreen
enemies, etc.
The game wes never supposed to be played even in widescreen, so...

**Comment by billywade** [comment]
Damb, I guess my dreams will stay dreams unless I buckle down and buy one of the remakes. Thanks!
