### ISSUE TITLE
Music Packs?

### ISSUE THREAD

**Issue by Nosh-Ware** [nxengine/nxengine-evo#127]
Hi, I was just wondering if its possible to make custom music sets, in the same way that the CS+ OSTs are put in. I know of a few artists who remixed basically all of the OST and would relay like to see it in the game. I would like to know if I could add this along side the other OST's.

**Comment by isage** [comment]
Yes, you can.
Create directory for your music in data/
Put there https://github.com/nxengine/nxengine-evo/blob/master/data/music.json and edit accordingly  if it's necessary to change filenames.
Add your folder to https://github.com/nxengine/nxengine-evo/blob/master/data/music_dirs.json

**Comment by Nosh-Ware** [comment]
Thanks dude!
