### ISSUE TITLE
Missing music

### ISSUE THREAD

**Issue by Nosh-Ware** [nxengine/nxengine-evo#128]
Where can I find the original .org files with there asset file names? It seems that even though I extracted my copy of cave story, it tries to access certain music files that it doesn't have. Could this be an issue with the extraction program, or is the entry in the wiki out of date and didn't have all the music files?

**Comment by isage** [comment]
>it tries to access certain music files that it doesn't have
For example?

>It seems that even though I extracted my copy of cave story
With extract, right? Can you provide it's output?

**Comment by Nosh-Ware** [comment]
![Screenshot from 2019-05-25 16-53-38](https://user-images.githubusercontent.com/30322411/58374940-c6e96e00-7f0d-11e9-9782-313cb733a100.png)
^My best attempt to display what is going on.

I tried a fresh download of CS from the link in the wiki, used an freshly compiled extract and nx and it still is missing sound files.
Even the title/plantation music is gone.
However, a track I have in the extracted contents, access, plays fine.

I noticed earlier in my first attempt to extract CS, that I had to get some font files from a pre-extracted copy of CS I found. After that, it seemed to work fine except for this, of course.

**Comment by isage** [comment]
What about log from extract?
Also, pre-extracted data is included in releases.
All needed font files are in data/ folder in git.

**Comment by Nosh-Ware** [comment]
Where is the extract log located on Linux?
Also I know that the font files didn't extract properly the first time, that was why I brought it up.
I'll poke around in how I compiled it to see if this is my setup or a possible bug.

**Comment by isage** [comment]
extract writes log to the console when you run it.
font files are not extracted, they are provided in this repo.

**Comment by Nosh-Ware** [comment]
Well, I rebuilt it, and it still seems to have the same issue, plus, it required me to copy over a whole bunch of files from other extracted CS copies I had. After that, it still had the same issue.

Here are the logs for the commands involved building (on linux):
[git.txt](https://github.com/nxengine/nxengine-evo/files/3222165/git.txt)
[cmake.txt](https://github.com/nxengine/nxengine-evo/files/3222164/cmake.txt)
[make.txt](https://github.com/nxengine/nxengine-evo/files/3222166/make.txt)

Oddly enough, I couldn't get a log form extract, at least when using the 'script' command, would it write a log to another place?

Here is the output form nx before I copied over all the assets form other CS extractions:
[nx.txt](https://github.com/nxengine/nxengine-evo/files/3222180/nx.txt)

**Comment by isage** [comment]
What 'script' command? Just run extract from the console.
Judging from the nx log you're either not running extract at all, or doing it wrong.

**Comment by isage** [comment]
Just download latest release, it has all required data already extracted.

**Comment by Nosh-Ware** [comment]
Unfortunately, it seems to have the same issue. I am not sure why.
The 'script' command just takes the output of the console and save it to a file.
The extract command does not print anything to the console when run. Could this be the issue?

**Comment by isage** [comment]
Can you provide screenshot of how you running it?

**Comment by Nosh-Ware** [comment]
In its current state, nx will not load graphically. I can also confirm that the files it says are missing, are missing.

Here is the full error log:
[log.txt](https://github.com/nxengine/nxengine-evo/files/3224932/log.txt)

It seems to be at the state I mentioned before I copied over the other /data files from other extractions.

**Comment by isage** [comment]
I'll ask one last time: please provide screenshot of you running extract.

And once again, all required files are proided in [released versions](https://github.com/nxengine/nxengine-evo/releases)

**Comment by Nosh-Ware** [comment]
I think there was a misunderstanding, extract does not output anything. Here is the output from it.
![Screenshot from 2019-05-28 12-37-41](https://user-images.githubusercontent.com/30322411/58499687-4b263600-8146-11e9-9c9f-4a5fd3ff43e7.png)
![Screenshot from 2019-05-28 12-38-15](https://user-images.githubusercontent.com/30322411/58499688-4b263600-8146-11e9-92ca-152528c1c4a6.png)

I didn't realise that the link in the linux building instruxctions got a diffrent vertion. Yes, the /data folder in released vertion fixes the issue.

**Comment by isage** [comment]
extract should be run from the current directory, not by a full path.
E.g. change directory to where your unpacked cavestory and extract binary
are and run it as ./extract
