### ISSUE TITLE
Unable to jump when block pushes you in Labyrinth I

### ISSUE THREAD

**Issue by mankeli** [nxengine/nxengine-evo#129]
In the original game, you can jump while pushed

**Comment by mankeli** [comment]
what?

**Comment by mankeli** [comment]
What did you do? Isn't this one of the files from original game?

**Comment by isage** [comment]
No, it's not. I made upper part of bounding box smaller, because it was triggered by quote getting stuck 1px into the block. It's not a perfect solution, but should work until total collision system rewrite.

**Comment by mankeli** [comment]
okay cool :+1: just wanted to understand how it was fixed
