### ISSUE TITLE
Sometimes unable to shoot near the cat boss in Labyrinth W

### ISSUE THREAD

**Issue by mankeli** [nxengine/nxengine-evo#130]
Player bullets (all weapons) begin to immediately hit some invisible wall somewhere between last elevator and cat boss, as if they would see everything as solid. This happens probably 50% of the time, and I've observed it happen in the middle of tunnel to boss from elevator, and sometimes on top of the elevator too.
If player backtracks from the "solid area", the shooting ability is regained. Insect bullets are not affected by this.

**Comment by isage** [comment]
Video would be nice, because i can't reproduce it

**Comment by mankeli** [comment]
I haven't got it either after posting this, will keep investigating

**Comment by mankeli** [comment]
It seems hard to repro. I got it again few times, but then I tried to find a solid repro but couldn't get it again. Somehow seems to be affected by elevator blocks. If Blade-to-solid collisions are determined by IsBlockedInShotDir() call in ai_blade_l3_shot(), could it be that moving blocks would be updated incorrectly to object?

**Comment by mankeli** [comment]
![image](https://user-images.githubusercontent.com/1931915/59600773-d45bd780-910a-11e9-95b6-d01b3bd65624.png)
seems that bounding boxes for those are messed up
