### ISSUE TITLE
Snap packaging fixes

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#131]
1) We need to rename snap package to nxengine-evo, because we can't officially use "Cave Story". This should be fixed in both snapcraft.yaml and .desktop file.
2) `snap` directory should be moved into `platform/`

**Comment by timsueberkrueb** [comment]
Hey, it appears like [renaming existing packages](https://forum.snapcraft.io/t/mechanics-of-renaming-snaps/940/7) is not supported, yet. I will have to publish a new package. The only downside of this is that existing users running the `cavestory` package won't get notified of this change (and stay on the last published revision). What I could do is publish a new revision to the old package with a dialog prompting them to switch.

Moving the `snap` directory will unfortunately break build.snapcraft.io (see https://github.com/canonical-web-and-design/build.snapcraft.io/issues/1094). It could be extracted back to a separate repository, though or we could use Travis CI or another ci system for building the snap (e.g. [Travis docs for snap](https://docs.travis-ci.com/user/deployment/snaps/)).

What do you think?

**Comment by isage** [comment]
Hm. Can we move snap/snapcraft.yaml to .snapcraft.yaml, and other files to platform/snap/ ?

**Comment by timsueberkrueb** [comment]
Yep, that should work.

**Comment by timsueberkrueb** [comment]
Okay, this would be the plan then:

* [ ] PR to rename package and move packaging
* [ ] Hook up build.snapcraft.io for new `nxengine-evo` package
* [ ] Request joystick interface autoconnect for new package in snapcraft forum
* [ ] Update `cavestory` package to show message box prompting users to switch to the new package

**Comment by timsueberkrueb** [comment]
I've prepared the migration. Users of the existing package will see this dialog, pointing them [to a wiki page](https://github.com/nxengine/nxengine-evo/wiki/Migrating-to-new-snap-package):

![nxengine-migration](https://user-images.githubusercontent.com/11774614/59833880-41f44780-9347-11e9-84b2-3b3094d8244b.png)

As snaps are usually strictly confined, there is no way for me to automatically migrate settings/game data between snap packages.

Is the current `master` stable enough for a release build of the new package or should I wait for the next release (I could also backport the snap config to the last release if it is urgent and master is not stable)?

**Comment by isage** [comment]
Current master is not stable. I think it's better to backport config to
last release.

**Comment by timsueberkrueb** [comment]
Done.
* `v2.6.4` has been released to `nxengine-evo`, `edge` channel.
* The migration prompt has been released to `cavestory`, `edge` channel

Next steps:
* [ ] stabilize new `nxengine-evo` package
* [ ] move migration prompt to beta/rc/stable (leave it in beta/rc for a while before promoting to stable)
* [ ] yank the `cavestory package`

Any objections?

**Comment by isage** [comment]
Nope, looks good

**Comment by timsueberkrueb** [comment]
Migration prompt is now in the stable channel of the old package. Going to leave it like this for a while and then I'm going to make the old package private (it's already unlisted).

**Comment by timsueberkrueb** [comment]
Migration complete.
