### ISSUE TITLE
Outer Wall bugs

### ISSUE THREAD

**Issue by Subc2** [nxengine/nxengine-evo#138]
In Outer Wall one Night Spirit always gets stuck and Sandcrocs sense Quote from greater distance.

Cave Story:
![original_bug4](https://user-images.githubusercontent.com/12563951/60771724-22517300-a0ec-11e9-8ca6-f22d62a59063.png)

NXEngine-evo:
![nxengine_bug4](https://user-images.githubusercontent.com/12563951/60771728-2d0c0800-a0ec-11e9-8218-03e25cce63ff.png)

**Comment by Subc2** [comment]
The problem with Sandcrocs has definitively been fixed. I am also unable to reproduce the stuck Night Spirit, so I think that the issue may be closed.

**Comment by isage** [comment]
Night spirit is probably the same old problem with bounding-boxes and collision detection
