### ISSUE TITLE
Other minor inconsistencies

### ISSUE THREAD

**Issue by Subc2** [nxengine/nxengine-evo#143]
I prepared a list of minor Cave Story compatibility problems:
- ~~In the Camp, Curly doesn't look down when Quote isn't nearby.~~
- ~~The lift in Core doesn't blink at all when not moving and blinks fast when in motion. In original CS it blinks constantly at the same rate.~~
- In Cthulhu's Abode? there is an invisible destroyable block, which (after destruction) changes to (randomly) 2exp, 2hp, 1 missile or solid 2hp heart (as in the original).
- Undead Core should open when the last message box is active.
- Undead Core should be closed (not open and empty) in its ending animation.
- Undead Core should disappear after the fight.
- ~~The crooked bed in Prefab House isn't crooked.~~

**Comment by Bonicgamer** [comment]
> * In Cthulhu's Abode? there is an invisible destroyable block, which (after destruction) changes to (randomly) 2exp, 2hp, 1 missile or solid 2hp heart (as in the original).

With my small bit of testing it seems to me that it being random is the issue.
For me in Cave Story, it always changes to a solid heart.
In nxengine-evo, it also changes to a solid heart, except when I use LV 3 or maxed charged Spur or Super Missiles (Haven't tested regular missiles) it randomly changes to 2exp, a blinking heart, or 1 missile oddly enough.

Also, according to [a fandom wiki page I just looked up](https://cavestory.fandom.com/wiki/Egg_Corridor%3F#Cthulhu.27s_Abode.3F) it seems like it should always be a solid heart.
