### ISSUE TITLE
Problem with <SAT

### ISSUE THREAD

**Issue by Subc2** [nxengine/nxengine-evo#144]
The skipflags are not honoured (tested on Core). It means that either `<SK+`, `<SKJ` or `<SAT` aren't working.

**Comment by isage** [comment]
They work(ed) fine in hell. I'll check.

**Comment by Subc2** [comment]
I did more testing and it's definitely the `<SAT` command misbehaving.

**Comment by isage** [comment]
`<SAT` has nothing to do with skipflags. It's an alias for `<CAT`

**Comment by isage** [comment]
Closing due to lack of feedback.

**Comment by Subc2** [comment]
It seems to be the problem with `<SAT`/`<CAT` implementation. `<SAT` is indeed very similar to `<TUR`. `<SAT` stops the instant text display on `<END` whereas `<TUR` stops it on either `<CLR`, `<EVE` or `<MSG` (I suppose we can also include `<END`, `<MS2` and `<MS3` for simplicity).

Currently the normal text display is restored on jumps if the text box is visible (which shouldn't break anything) and on commands `<MSG`, `<MS2` and `<MS3`, which breaks all 6 occurrences of `<SAT`.

**Comment by isage** [comment]
I still don't understand what's the problem. Can you provide comparison on how it works in freeware and how in nxevo?

**Comment by Subc2** [comment]
If you die to Omega, Core, etc. and you go there again without reloading the game (so skipflags won't reset); in the original version, the text in most (if not all) dialog boxes appearing before the fight will display instantly.

**Comment by isage** [comment]
Yep. That i can reproduce.

That's actually a little more complicated.
So, `<TUR` sets one flag (let's call int FAST_DISPLAY)
`<MSG`, `<MS2`, `<MS3` and `<CLO` clear that flag. That's why `<TUR` goes after `<MSG` etc. in scripts.

`<SAT` sets different flag. If `<MSG`, `<MS2`, `<MS3` see that flag, they set FAST_DISPLAY flag by themselves. Flag set by `<SAT` is resseted only on script start/end (jumps do not reset this flag)

**Comment by Subc2** [comment]
`<CLR` is frequently used with `<TUR` and disables it. `<CLO` actually doesn't need to turn off `<TUR` because the next `<MSG`, `<MS2` or `<MS3` will do it. I agree with the rest of your comment.

**Comment by isage** [comment]
According to CSE2 sources, `<CLR` just clears textbox, it's not changing any flags.
`<CLO` removes all flags, except flag set by `<SAT`

**Comment by Subc2** [comment]
I based it on the following line from Cave Editor config file:
```
<TUR    0       ----    Text UnRead?    Instant text display until CLR
```

I didn't find a `<TUR`+`<CLR` use case in the original game where it would make a difference though.
