### ISSUE TITLE
Not gameplay-related issues

### ISSUE THREAD

**Issue by Subc2** [nxengine/nxengine-evo#145]
I found out the following not gameplay-related incompatibilities:
- Map system can't be closed with Z key (in original Cave Story it can) and can be closed with W key (in original it can't).
- The game cannot be paused when the falling island animation is displayed.

**Comment by isage** [comment]
1) That's intended. It closed by either map key, or button assigned to "Cancel" in settings (eg, fire or jump). While it's not as in original game, IMHO it's more logical.

**Comment by Subc2** [comment]
The "arms and items" menu brought up with the Q key can be closed with the Z key (along with Q and X). It would be more consistent if map system were closeable with Z, X and W keys.

On a side note, I discovered that when I highlight other (not currently used) weapon, select an item and close the menu (with either X or Q), the weapon isn't changed (unlike in the original). Also, using the map system from the "arms and items" menu makes the game "forget" which weapon was highlighted and defaults to the currently used one.
