### ISSUE TITLE
Decoding ORG music is CPU intensive

### ISSUE THREAD

**Issue by Subc2** [nxengine/nxengine-evo#147]
When I run NXEngine-evo on a computer with 1 core 64-bit processor, playing "Original" music; the game starts lagging and the music stutters. It is not the case when the "New" or "Remastered" music is selected in the sound options. I compared CPU usage among different scenarios and thats the results:

| CPU  | description                                   |
| ---: | :-------------------------------------------- |
|  ~5% | idle system                                   |
| ~45% | NXEngine-evo, "Remastered" music, Start Point |
| ~70% | NXEngine-evo, "Original" music, Start Point   |
| ~45% | Cave Story, Start Point                       |

**Comment by isage** [comment]
Can you try rebuilding with -DLOW_END_HARDWARE=ON and see if this helps?

**Comment by Subc2** [comment]
Yes, it completely fixed the performance problem. I genuinely hadn't noticed this option.

**Comment by isage** [comment]
I will probably add an ingame option to toggle music postprocessing
