### ISSUE TITLE
Santa glitches and goes down

### ISSUE THREAD

**Issue by maxlefou** [nxengine/nxengine-evo#153]
In Grasstown, when you get the key and deliver it to Santa, instead of going straight to his house's door, he clips down the ground, like in the gif below:
![Image from Gyazo](https://i.gyazo.com/bbf658cd65e587a0bf68f68ce8c8a2e9.gif)

Thankfully, for some odd reason, it doesn't prevent him to actually go inside the house and do the stuff he actually does. :p 

Happens with both english and french language so it's normally not related to the translation files. (haven't tried the other languages though)

**Comment by 16BitWonder** [comment]
Was this with the latest source, or the v2.6.4 release?
This issue looked like it was fixed already.
https://github.com/nxengine/nxengine-evo/issues/122

**Comment by maxlefou** [comment]
the release one
