### ISSUE TITLE
Random crashes while fighting the core

### ISSUE THREAD

**Issue by maxlefou** [nxengine/nxengine-evo#155]
As title says. (i speak of the first core battle, not the one at the end)

Can't tell what makes it crash since it can crash at the beginning of the fight, or later in it. There's no errors displayed either, it just seems to lag suddenly and then crash. (any way to activate debug logs on release or anything? )

**Comment by isage** [comment]
Latest git or latest release?
Debug logs are only activated at build time

**Comment by maxlefou** [comment]
latest release. so i guess there's no way to give logs?

**Comment by mesekoc123** [comment]
Just chiming in to tell you I experience the same thing, stuck at the core because it crashes after a while. I'm not sure if it crashes after a certain time has passed of once the core got down to a certain health level.

**Comment by LoneTiger** [comment]
Same issue here, game crashes after fighting the core for a couple minutes. Using the latest release. Playing on 64bit Windows 10, in case that's relevant.

**Comment by maxlefou** [comment]
I tried recently, still with the same build, and I finally could go through the core without crashing. Though, I still could get random crashes by entering the next section (with all the water and the shelter where you can drain water from curly)

**Comment by Gwarthog** [comment]
I get the same error, during boss fight the game stops and the window error comes out. I'm on ps vita, I hope there's a way to fix it ( error c2-12828-1)

**Comment by Redecorating** [comment]
On Windows I've seen it crash almost exactly 2 minutes after the dialog before the core fight finishes three times. (Thus if you speedrun the fight you can progress)
