### ISSUE TITLE
Is it possible for this to run at 60 FPS? And if so, how?

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [nxengine/nxengine-evo#157]
I've been looking up some things and it turns out it's possible to run Freeware CS at 60 FPS. So can this possibly get the same treatment? And if so, how? But if not, is it at least compatible with CS editing tools like Booster's Lab?

**Comment by 16BitWonder** [comment]
See issue #6

**Comment by Al-AmeenAdewunmi** [comment]
> See issue #6

I've seen it, but I can't really understand it. What's "game.h"?

**Comment by 16BitWonder** [comment]
game.h is one of the header files, while statusbar.cpp is one of the source files.

They can be found here:
https://github.com/nxengine/nxengine-evo/blob/master/src/game.h
https://github.com/nxengine/nxengine-evo/blob/master/src/statusbar.cpp

**Comment by Al-AmeenAdewunmi** [comment]
> game.h is one of the header files, while statusbar.cpp is one of the source files.
> 
> They can be found here:
> https://github.com/nxengine/nxengine-evo/blob/master/src/game.h
> https://github.com/nxengine/nxengine-evo/blob/master/src/statusbar.cpp

Okay, so how do I implement it?

**Comment by 16BitWonder** [comment]
Make the same changes that rea987 did in the issue I linked and then build the application.

**Comment by Al-AmeenAdewunmi** [comment]
Okay, I created my branches. Now what?
![Screenshot (278)](https://user-images.githubusercontent.com/53586162/64914993-8af44600-d754-11e9-80c8-98f824953528.png)

**Comment by 16BitWonder** [comment]
Merge them into a single branch and then follow the building instructions for your platform.
https://github.com/nxengine/nxengine-evo/wiki

**Comment by Al-AmeenAdewunmi** [comment]
They're both pull requests now. If that's what I'm supposed to do.

**Comment by Al-AmeenAdewunmi** [comment]
I have the branch, now I just need to run the sln file. Any programs I can use for that?

**Comment by 16BitWonder** [comment]
> 
> 
> I have the branch, now I just need to run the sln file. Any programs I can use for that?

You can open the solution (.sln) file with Visual Studio and compile the project from there.

**Comment by Al-AmeenAdewunmi** [comment]
Yes, I tried that. But apparently I'm gonna need 6 GB of storage. Is that really necessary?
![Screenshot (280)](https://user-images.githubusercontent.com/53586162/64916022-e29eab80-d76c-11e9-8c58-e5edc5a5aacf.png)

**Comment by 16BitWonder** [comment]
If you would like to compile a C++ project with Visual Studio then yes, the 6GB are necessary.

It's a full IDE, I'm honestly surprised it's _only_ 6GB.

**Comment by Al-AmeenAdewunmi** [comment]
So what I did is that I loaded up the solution, right-clicked "nx" and pressed "Build". Is that correct?

Regardless, I kept running into this error ""CL.exe" exited with code 1."
![Screenshot (282)](https://user-images.githubusercontent.com/53586162/64918535-ac2a5600-d797-11e9-8190-1db87d44a940.png)

**Comment by 16BitWonder** [comment]
Yes that's correct way to build it.
In the bottom right of your Error list window, click on 'Output' to get more detailed logs and research how they may be fixed.
I'm assuming you're missing some dependency or using an incorrect build environment version.

**Comment by Al-AmeenAdewunmi** [comment]
I'm still looking it up, but I'll just leave this here for now.

1>Generating Code...
1>C:\Users\alame\Documents\GitHub\nxengine-evo\src\trig.cpp : fatal error C1090: PDB API call failed, error code '3': C:\Users\alame\Documents\GitHub\nxengine-evo\platform\win32\nx\x64\Debug\vc142.pdb
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: "CL.exe" exited with code 1.
1>Done building project "nx.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Al-AmeenAdewunmi** [comment]
Okay, so I think I was finally able to build the platform. These are the results.
![Screenshot (288)](https://user-images.githubusercontent.com/53586162/64987460-1a1e6c80-d8c1-11e9-889f-19fe5c1db7c1.png)

However, when I clicked on nx.exe, I got this:
![Screenshot (286)](https://user-images.githubusercontent.com/53586162/64987490-30c4c380-d8c1-11e9-9cf3-2b1e295cb159.png)

**Comment by 16BitWonder** [comment]
I don't know that I've encountered that error before.
I notice you have a lot of extra files after compiling, I only end up with four.
Are you still building the solution by right clicking nx and selecting build?

**Comment by Al-AmeenAdewunmi** [comment]
Well, I went to "Analyze and Code Cleanup" and then selected "Run Code Analysis on nx". I still ran into errors when I selected the Build option, so I was surprised to see there was another way.
Also, some of the files you see are because nx.EXE kept bringing up .DLL errors.

**Comment by 16BitWonder** [comment]
Try copying all the .DLLs from platform/win32/ext/runtime/x64 into that folder and try it again.
If that doesn't work I can just compile it later tonight with the changes you want.

**Comment by Al-AmeenAdewunmi** [comment]
The .EXE loaded up, but...
![Screenshot (290)](https://user-images.githubusercontent.com/53586162/65117606-0fa7c400-d9e2-11e9-9475-7875e7cf9ba4.png)

**Comment by 16BitWonder** [comment]
That means it's working.
All you need now is a working data folder in the same directory as the .exe.
Go to the releases page ([https://github.com/nxengine/nxengine-evo/releases](url)) and grab the data folder from the current win64 release and place it in the same directory as your .exe.
Then copy the contents of the data folder in nxengine-evo/data to your data folder, overwriting if prompted.

**Comment by Al-AmeenAdewunmi** [comment]
Yes! It works now. Thanks for the help.

**Comment by Al-AmeenAdewunmi** [comment]
Just one last question. Kinda unrelated but still.

Do you know anything that can record the game for me?

**Comment by 16BitWonder** [comment]
I use OBS Studio.
