### ISSUE TITLE
Please add spanish language by Orden

### ISSUE THREAD

**Issue by t33st33r** [nxengine/nxengine-evo#164]
I have downloaded the language patch (well... it is the full translated game for windows actually) but I don't know where to put those files. I am using PSVita.
I have a hacked Switch too but I have no idea where to put those files in Switch's SD.

Can you add that spanish translation to your project? Thanks in advance.

Here it is: http://www.romhacking.net/translations/2172/

**Comment by isage** [comment]
Sure, but I'll probably need help with translating menu items.

**Comment by t33st33r** [comment]
Loading: Cargando
New game: Empezar
Load game: Continuar
Options: Opciones
Mods (can keep untouched)
Quit: Cerrar

Options menu:
```
Graphics: Gráficos
Sound: Sonido
Controls: Controles
Language > Lenguage: Español
Return: Volver
```

Graphics menu:
```
Resolution: Resolución
Fullscreen: Pantalla completa
Animated facepics: Avatares animados
Return: Volver
```

Sound menu:
```
Music: Música
Tracks: Pistas
· Original: Original
· Remastered (in case you choose this word for remastered tracks): Remasterizadas
· Chiptunes: (in case you choose this word) > This can keep untouched
Sound: Sonido
SFX volume: Volumen de efectos
Music volume: Volumen de música
Return: Volver
```

Controls menu:
```
Force feedback: Forzar feedback
Strafing (can keep untouched)
· Ok: Aceptar
· Jump: Salto
· Cancel: Cancelar
· Fire: Disparo
Bind keys: Redefinir teclas
```

Bind keys menu:
```
Left: Izquierda
Right: Derecha
Up: Arriba
Down: Abajo
Strafe (can keep untouched)
Fire: Disparo
Wpn Prev: Arma anterior
Wpn Next: Arma siguiente
Inventory: Inventario
Map: Mapa
Pause: Pausa
Return: Volver
```

Pause menu:
```
Resume: Continuar
Options: Opciones
Reset: Reiniciar
Quit: Cerrar
```

:)

Suggestion (for controls menu): It'd be easier to translate (for any language... I think so) if you replace "Ok" by "Cross" and "Cancel" by "Circle"

**Comment by isage** [comment]
Hm. Looks like Orden's translation is based on Vagrant Traducciones one (only .tsc files differ) and the problem is, not all map names are translated (i've "translated" some using previous translations):
```
 "Boulder Chamber": "Boulder Chamber",
  "Labyrinth M": "Laberinto M",
  "Dark Place": "Dark Place",
  "Core": "Core",
  "Waterway": "Waterway",
  "Egg Corridor?": "Pasillo Oval?",
  "Cthulhu's Abode?": "Choza de Cthulhu?",
  "Egg Observation Room?": "Sala de Observación de Huevos?",
  "Egg No. 00": "Huevo No. 00",
  "Outer Wall": "Outer Wall",
  "Side Room": "Side Room",
  "Storehouse": "Storehouse",
  "Plantation": "Plantación",
  "Jail No. 1": "Jail No. 1",
  "Hideout": "Hideout",
  "Rest Area": "Rest Area",
  "Teleporter": "Teleporter",
  "Jail No. 2": "Jail No. 2",
  "Balcony": "Balcony",
  "Final Cave": "Final Cave",
  "Throne Room": "Throne Room",
  "The King's Table": "The King's Table",
  "Prefab Building": "Prefab Building",
  "Last Cave (Hidden)": "Last Cave (Hidden)",
  "Black Space": "Black Space",
  "Little House": "Little House",
  "Balcony": "Balcony",
  "Fall": "Fall",
  "Waterway Cabin": "Waterway Cabin",
  "Prefab House": "Prefab House",
  "Sacred Ground - B1": "Sacred Ground - B1",
  "Sacred Ground - B2": "Sacred Ground - B2",
  "Sacred Ground - B3": "Sacred Ground - B3",
  "Storage": "Storage",
  "Passage?": "Passage?",
  "Statue Chamber": "Statue Chamber",
  "Seal Chamber": "Seal Chamber",
  "Corridor": "Corridor",
  "Hermit Gunsmith": "Hermit Gunsmith",
  "Clock Room": "Clock Room",
```

**Comment by t33st33r** [comment]
"Boulder chamber": "Cámara de la roca"
"Labyrinth M": "Laberinto M"
"Dark place": "Lugar oscuro"
"Core": "Núcleo"
"Waterway": "Camino de agua"
"Egg Corridor?": "¿Zona de gestación de huevos?"
"Cthulhu's abode": "Morada de Cthulhu"
"Egg Observation Room?": "¿Sala de observación?" (Literal translation is "¿Sala de observación de huevos?" but "huevos" is plural and there is only one so I decided to translate it as if the original term was "Observation Room"... it is obvious what they observe in the room because it is next to "egg corridor" and there is an egg in the middle of this room)
"Egg No. 00": "Egg nº 00" (if you can't use "º" the right alternative is "Huevo 00")
"Outer Wall": "Exterior"
____
Consider this a draft... I will continue this translation in next days (editing this comment and making a new one once it is finished).

I need help to identify some of this places (a translation based on context is better than a literal one).

**Comment by isage** [comment]
I've added https://github.com/nxengine/lang_spanish you can submit pull-requests there

**Comment by sodomon2** [comment]
I tried the spanish translation when I started the nxengine-evo, the translation is loaded and the menus are translated but when I play, no dialog is in spanish as you can see in the image

![1](https://user-images.githubusercontent.com/49420637/96385310-0cd94e80-1161-11eb-9290-16ee15d68fb7.png)
![2](https://user-images.githubusercontent.com/49420637/96385312-0fd43f00-1161-11eb-9952-5abfd32eda8b.png)

and also it seems that the ascents are not recognized 

![error](https://user-images.githubusercontent.com/49420637/96385350-4611be80-1161-11eb-8e5c-d2f49902897d.png)

**Comment by isage** [comment]
And how did you tried it? Let me guess, just cloned git repo?
That wont work, as scripts need to be encoded, and font files generated. 
You can get prebuilt translation here https://github.com/nxengine/translations/releases/tag/v1.10

**Comment by isage** [comment]
And how did you tried it? Let me guess, just cloned git repo?
That wont work, as scripts need to be encoded, and font files generated. 
You can get prebuilt translation here https://github.com/nxengine/translations/releases/tag/v1.10

**Comment by sodomon2** [comment]
don't actually clone me https://github.com/nxengine/lang_spanish 

so I think it's a mistake by nxengine-evo himself

**Comment by sodomon2** [comment]
@isage  oh,great the pre-built version has no errors

**Comment by sodomon2** [comment]
oh,great the pre-built version accepts the ascents,and the dialogs are translated but there are still errors,like these for example

![error](https://user-images.githubusercontent.com/49420637/96386887-524f4900-116c-11eb-8194-92c1fbc9d67d.png)
![error2](https://user-images.githubusercontent.com/49420637/96386896-6004ce80-116c-11eb-9bcf-81770f67ad84.png)
![error3](https://user-images.githubusercontent.com/49420637/96386927-a0fce300-116c-11eb-8b12-20ab28dfccda.png)

and also the game hangs as soon as the kazuma intro is finished

![error4](https://user-images.githubusercontent.com/49420637/96386931-a6f2c400-116c-11eb-9a30-167626165f24.png)

maybe it's because I'm not using the git version

**Comment by isage** [comment]
https://github.com/nxengine/translations/releases/tag/v1.11

**Comment by sodomon2** [comment]
ok it seems that the first errors have been fixed

![fix](https://user-images.githubusercontent.com/49420637/96387968-f5579100-1173-11eb-83e7-dd6f1af578de.png)

but the crashing error is still intact

![error](https://user-images.githubusercontent.com/49420637/96388048-5e3f0900-1174-11eb-8cb5-adaf8095b556.png)

and when it passes the crashing gives this error in the output

```
load_meta: 'data/StageMeta/Start.json' finished parsing
StageBossManager::SetType(0)
-- Starting on-entry script 91
 error << StartScript: no script at position #0091 page 1! >>

```

**Comment by isage** [comment]
https://github.com/nxengine/translations/releases/tag/v1.12

**Comment by sodomon2** [comment]
ok it seems that it already works well

**Comment by isage** [comment]
I'll close that when we finally release version with it included
