### ISSUE TITLE
[v2.6.4] Horrible frame-rate and music stuttering

### ISSUE THREAD

**Issue by Zanmato27** [nxengine/nxengine-evo#166]
I was trying to install this from the latest Windows builds but I am getting terrible frame-rate and the music is stuttering and becoming garbled as a result. I don't get why I have this problem, my PC should be more than capable to run this engine. I have tried both 32-bit and 64-bit versions and my performance with this engine has been horrible.

**Comment by isage** [comment]
Please provide debug.log

**Comment by Zanmato27** [comment]
I am not sure if this is it because it didn't dump a file with that name but I got this instead in the attachments
[d.txt](https://github.com/nxengine/nxengine-evo/files/4106237/d.txt)
.

**Comment by isage** [comment]
It is. Looks good to me (pxt errors can be ignored).
What video card are you using?

**Comment by deltz025** [comment]
Same sound issue here, but no noticeable framereate issues. I'm running with a GTX 1650 and an integrated Intel 630, both produce the same choppiness. Also tried 2.6.3, and it runs like a dream. 

[debug.log](https://github.com/nxengine/nxengine-evo/files/4168638/debug.log)

**Comment by Zanmato27** [comment]
I am using an Nvidia GeForce GTX 960 and I had this problem.

**Comment by SViN24** [comment]
definitely audio stuttering here too with an RX560

**Comment by isage** [comment]
Should be fixed with latest release and default music interpolation setting.
