### ISSUE TITLE
Game doesn't start when Visual C++ Redistributable for Visual Studio 2015 isn't installed, vcruntime140.dll and msvcp140.dll missing

### ISSUE THREAD

**Issue by damian101** [nxengine/nxengine-evo#168]
The game wouldn't start, it said it couldn't find vcruntime140.dll and msvcp140.dll . Fixed by installing Visual C++ Redistributable for Visual Studio 2015.
I think it would make sense to include the additional dlls in the zip file or write a small readme where this dependency is listed or just include an offline installer for the Visual C++ Redistributable for Visual Studio 2015 package.

**Comment by Clownacy** [comment]
There's also the option of [using the static runtime library](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019), so that the DLLs are basically embedded in the EXE. This is what the original Cave Story EXE did.
