### ISSUE TITLE
Provide data dumping functionality

### ISSUE THREAD

**Issue by bentley** [nxengine/nxengine-evo#170]
Some data files in the repository have been extracted or otherwise converted from the original Cave Story data files. But Pixel, the copyright holder, never provided general permission to redistribute, modify, or convert these files. In most countries, these rights are exclusive to the copyright holder by default.

Debian makes it clear that this copyright issue prevents them from packaging nxengine-evo for their system: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896714

Speaking as an OpenBSD developer, this issue limits us in the same way. We cannot provide nxengine-evo packages as-is.

If nxengine-evo provided a script or other functionality a player could use to automatically download and extract the data assets from the original sources (studiopixel.jp and Aeon Genesis), rather than redistributing copyrighted assets, all would be well. If my memory is correct, Katy’s original nxengine had this functionality. If it were reintroduced, free operating systems like OpenBSD and Debian could provide nxengine-evo packages to our users.

**Comment by isage** [comment]
There's binary (with source code), called literally that - "extract"

**Comment by isage** [comment]
And if that's doesn't help, there's https://github.com/nxengine/nxengine-evo/blob/master/build-appimage.sh and appveyour/travisci scripts

**Comment by isage** [comment]
As you can figure out, there's no way for me to provide automatic ways to re-draw mimiga-mask end pictures, animated facepics and widescreen backgrounds.

**Comment by bentley** [comment]
Thanks for the clarification: for unmodified assets, the functionality already exists, and there’s no way to “extract” the modified assets since they never existed as‐is elsewhere. So there’s nothing more to be done in this thread.

**Comment by isage** [comment]
You can write a wrapper script to grab and extract unmodified assets, as well as grab modified assets from github. That way it should be fairly safe legal-wise.
