### ISSUE TITLE
Audio Stuttering fix?

### ISSUE THREAD

**Issue by Tert1947** [nxengine/nxengine-evo#173]
Make the low end hardware audio fix an option in Audio please. It would save many people with laptops and low-end PCs from having to dive their noses into C++ without any prior knowledge of it.

**Comment by Kittymayor42** [comment]
I'm also having this issue. Is there anyway I can go in and fix it myself? Love this game, but the sound is kinda ruining my enjoyment. I'm running Ubuntu 20.04, for reference

**Comment by isage** [comment]
Yes, you can build from source. That was fixed long time ago.
