### ISSUE TITLE
Pulse sounds off

### ISSUE THREAD

**Issue by Cristian101400** [nxengine/nxengine-evo#175]
I don't know if this is something you can fix exactly. But pulse on here sounds very off, maybe you could look into it? Thank you.

**Comment by isage** [comment]
What? What pulse?

**Comment by Tert1947** [comment]
Pulse is a track in the game. It can be heard in the room for Egg No. 00 and Post-Labyrinth Arthur's House, as well as the shack where Curly gets the water drained out of her from the Core boss fight in the Waterway.

**Comment by isage** [comment]
Is that still reproducible with latest version?

**Comment by Cristian101400** [comment]
I can check, I'll report back about it in the discord server. My username
is Grabondese#7777
