### ISSUE TITLE
Spur gun can't level up

### ISSUE THREAD

**Issue by Aierbote** [nxengine/nxengine-evo#176]
Decided to try this secret upgrade of the basic gun (Polar Star) and after all the effort (cons of not having the Machine Gun)

But the [Spur](https://cavestory.fandom.com/wiki/Spur) gun can't level up, each bunch of experience "coins" I get seems to never fill its experience bar.

I tried even to get the [Whimsical Star](https://cavestory.fandom.com/wiki/Whimsical_Star) since it works together with the Spur. 

This last "trinket" works well (it can reach three stars, meaning LVL 3) by collecting enough XP, hence it seems the Spur XPs are collected and leveling up the Stars but not the Spur somehow

**Comment by nlburgin** [comment]
It's supposed to do that.

It ignores exp chips, but instead uses the level-up meter as a "charged shot" system if you hold the trigger down.

**Comment by Aierbote** [comment]
LOL. Okay, thanks! I guess I didn't it carefully last night!

**Comment by JL2210** [comment]
I'm not sure how accurate the fandom is, but it does say that the Spur levels up, though you can't see it.
