### ISSUE TITLE
Big area maps crash or slow game.

### ISSUE THREAD

**Issue by YumeDragoon** [nxengine/nxengine-evo#177]
I found that on my vita whenever I try opening any area map that is big (ex. Sand Zone, Certain Labyrinth Maps, Etc.) The game will begin to slow and then crash near the end of loading the map. I use the map quite a bit in Cave Story and this is really inconvenient. I'm not sure if this happens on any other versions.

**Comment by CreamYT** [comment]
update. when testing on pc is slows alot but never crashes. This should be looked into

**Comment by B4rabbas** [comment]
Yeah I've this problem too, very slow gameplay, very strange

**Comment by isage** [comment]
> update. when testing on pc is slows alot but never crashes. This should be looked into

Built from source or downloaded from releases?

**Comment by B4rabbas** [comment]
Hi Isage,
I've tried on compiled version and also from release section.
And on linux there is visuals glitches too

**Comment by CreamYT** [comment]
I just grabbed mine from releases

**Comment by isage** [comment]
Should be fixed in latest release
