### ISSUE TITLE
[Switch] v2.6.4 Binary needs recompiled with newer libnx for 9.0.0+ input support

### ISSUE THREAD

**Issue by 16BitWonder** [nxengine/nxengine-evo#186]
In September last year a system update was released for Nintendo Switch (9.0.0) that broke input in homebrew, and a subsequent fix was released in [libnx v2.5.0](https://github.com/switchbrew/libnx/releases/tag/v2.5.0) a few days later.

This issue can be circumvented via an hid-mitm that is currently present in [Atmosphere-NX](https://github.com/Atmosphere-NX/Atmosphere), however it has been noted that as of the [0.10.2 release](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.10.2) this mitm is disabled by default and may be removed in the future.

To resolve input issues on system versions 9.0.0+ the application needs to be recompiled with libnx v2.5.0 or newer.

**Comment by isage** [comment]
Noted, thanks. I'm (finally) preparing new release, so it should be fixed then

**Comment by dj5927** [comment]
I want to run on the 12.2 firmware for the switch.
When are your plans for the update?

**Comment by 16BitWonder** [comment]
Here's a dirty build of [8044ebd](https://github.com/nxengine/nxengine-evo/tree/8044ebdd5a5b3f8ea136f1e0ee95dc406400dcd8) if you'd like to try that while waiting for a full release.
[NXEngine-Evo-2.6.5-8044ebd.zip](https://github.com/nxengine/nxengine-evo/files/6516953/NXEngine-Evo-2.6.5-8044ebd.zip)

**Comment by dj5927** [comment]
thankyou

https://drive.google.com/file/d/1hPYKu4uriSU5RyhagY7yVlnIlR3J1eBt/view?usp=sharing

To the next release
Please add a Korean version.
You can get it from the link above.

With this Korean patch
vita and
I went from Odroid to the ending without any problems.

**Comment by dj5927** [comment]
I'll ask you one more question.

Is there a way to use custom sound on the switch?

**Comment by 16BitWonder** [comment]
Fixed with release [2.6.5](https://github.com/nxengine/nxengine-evo/releases/tag/v2.6.5)
