### ISSUE TITLE
Transfer snap to nxengine organization account

### ISSUE THREAD

**Issue by timsueberkrueb** [nxengine/nxengine-evo#190]
It would be great if we could create a shared organization account in the snap store. Currently the snap package lives under my personal snap store username (`timsueberkrueb`). By creating an official `nxengine` account we would indicate that the snap package is official.

Recommended steps:

* [x] @isage creates a new Ubuntu One account (e.g. called `nxengine`) at https://login.ubuntu.com
* [x] @timsueberkrueb requests a transfer of the snap package to `nxengine` in the [snapcraft forum](https://forum.snapcraft.io/)
* [ ] @isage adds @timsueberkrueb (or anyone else interested in maintaining the snap) as a collaborator ([link](https://dashboard.snapcraft.io/snaps/nxengine-evo/collaboration/))
* [ ] @timsueberkrueb (if possible) / @isage (if needed) reenables the automatic snap builds under http://snapcraft.io/nxengine-evo/builds

**Comment by isage** [comment]
I've created `nxengine-evo` ubuntu one account

**Comment by timsueberkrueb** [comment]
Great, thank you :) I've requested the transfer in [this forum post](https://forum.snapcraft.io/t/transfer-nxengine-evo-to-nxengine-evo/20671).

**Comment by timsueberkrueb** [comment]
Hey @isage, I invited you via email as requested [in the reply to the forum post](https://forum.snapcraft.io/t/transfer-nxengine-evo-to-nxengine-evo/20671).

**Comment by isage** [comment]
I think you should've invited nxengine-evo instead of me. It's registered
to different email (nxengine.evo@gmail.com)

**Comment by timsueberkrueb** [comment]
Apologizes, done :)

**Comment by isage** [comment]
Accepted

**Comment by isage** [comment]
Snap got transferred and it looks like it automatically added you as collaborator

**Comment by timsueberkrueb** [comment]
Awesome, thank you!
