### ISSUE TITLE
Feature Request: Updated Portraits

### ISSUE THREAD

**Issue by Jinraider** [nxengine/nxengine-evo#195]
One feature I'm happy that this build of the Freeware Cave Story has is the animated portraits. However, they still use the portraits from the freeware version, which can be a bit off-putting (especially Misery, who features an entirely different hair colour).

Rips of the portraits from other versions of Cave Story are easy to find, such as the Switch version, which also feature animated portraits (and may be larger and clearer than the current ones used). I'm wondering if it's possible to implement those into the build in the future, or would it be subject to legal issues?

Anyway, I got the sprites I referred to from here: https://www.spriters-resource.com/nintendo_switch/cavestoryplus/sheet/94487/ Hope you'll consider this feature.

**Comment by isage** [comment]
It would be subject to legal issues

**Comment by Jinraider** [comment]
I wonder if updating the portraits as is would incur any issues. Would changing the existing Misery portrait to have blue hair ourselves have issues associated with it?

**Comment by isage** [comment]
I would be an issue to me, because i like her with green hair.

**Comment by Jinraider** [comment]
Fair enough, I guess.
