### ISSUE TITLE
How to implement custom soundtracks?

### ISSUE THREAD

**Issue by Jinraider** [nxengine/nxengine-evo#196]
As topic; I don't know how to mod in custom soundtracks to the build

**Comment by isage** [comment]
Edit `music_dirs.json`  
If your files named differently, you can include "playlist" json item in the same format as in `music.json`.  
Only ogg is supported for custom soundtracks.  
If only part on track should be looped it should be split into `<name>_intro.ogg` and `<name>_loop.ogg`,
