### ISSUE TITLE
Glow effect too intense for undead core and doctor boss fights 

### ISSUE THREAD

**Issue by timsueberkrueb** [nxengine/nxengine-evo#202]
Hey, the glow effects are overall pretty nice, but I think they're too intense for the boss fights against the undead core and the doctor

<details>
<summary>Warning: end game spoiler</summary>

![cave_story_glow1](https://user-images.githubusercontent.com/11774614/103638549-590c8180-4f4d-11eb-8e37-5f132835b711.png)

![cave_story_glow](https://user-images.githubusercontent.com/11774614/103638556-5ad64500-4f4d-11eb-9050-ecc568fdf175.png)
</details>

**Comment by isage** [comment]
Thanks! Toned it down a little.
