### ISSUE TITLE
No updated OSX version?

### ISSUE THREAD

**Issue by clemdawn** [nxengine/nxengine-evo#203]
The 2.6.5-rc2 version doesn't have any .dmg file or anything. And the latest built version of this project for Mac was released on April 2019, so I assume it won't work for Mac Big Sur (OS 11). Do I have to build the latest version myself? Or is there any available way to play Cave Story in Mac nowadays?

**Comment by isage** [comment]
Wait a little, I'll release new version soon. rc version was intended for
translator.

**Comment by clemdawn** [comment]
Thank you <3 do you happen to know any other methods to play the game on mac meanwhile? in any case i'll wait for the update :-)
