### ISSUE TITLE
Selecting 4k resolution crashes

### ISSUE THREAD

**Issue by Kojlax** [nxengine/nxengine-evo#205]
Running on Manjaro Linux 5.10.7-1, compiled from latest commit.

Selecting any resolution above 2560x1440 immediately crashes, with the following console log:

```
[15:45:31.685] [info] [Renderer.cpp:170 setResolution]: Renderer::setResolution(13)
[15:45:31.685] [info] [Renderer.cpp:193 setResolution]: Setting scaling 8
[15:45:32.188] [error] [Font.cpp:68 load]: Error opening font file data/font_8.fnt
[15:45:32.212] [warning] [Font.cpp:110 glyph]: No glyph for codepoint 82
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)
```
This crash occurs, with identical error log, with fullscreen both on and off, as well as with extra monitors disabled.

~~A secondary, and much less important issue, is that the menu pulls its list of resolutions from the primary monitor, instead of the current one. So, if the primary monitor is a 1080p monitor, but the monitor the game's fullscreened on is 2160p, its impossible to go above 1920x1080.~~

**Comment by isage** [comment]
Yeah, there are no fonts generated for those scalefactors. I think, though, we should just draw them upscaled

**Comment by isage** [comment]
Second issue (which should've been reported separately) should be fixed with latest commit.

**Comment by Kojlax** [comment]
sorry, I didn't think it was big enough to deserve its own issue

**Comment by isage** [comment]
It just makes tracking things easier

**Comment by isage** [comment]
Semi-fixed with latest commit. Falls back to smallest font in case font for current scale not found. Still need to update translations generator with more font sizes. And maybe fallback to largest available font below current one.
