### ISSUE TITLE
Character jitters and shakes when paused in Fullscreen. 

### ISSUE THREAD

**Issue by Mister-Dolus** [nxengine/nxengine-evo#21]
Downloaded the game from the AUR in Manjaro Linux. Everything seems to be working fine, but one minor thing I've noticed is that the character will basically vibrate if they were in motion before you pause. This, however, only happens when in fullscreen mode.

**Comment by Mister-Dolus** [comment]
After testing in a larger area, it seems to be the whole screen will also do this when the camera is panning before you hit pause.

**Comment by isage** [comment]
Confirmed.
I'll take some time to fix this, as i'm currently working on rather large changeset to allow translations.

**Comment by isage** [comment]
Fixed in latest release
