### ISSUE TITLE
Having trouble with Cmake when building on Linux

### ISSUE THREAD

**Issue by Kittymayor42** [nxengine/nxengine-evo#213]
Hi there, 
I'm trying to build from source on Ubuntu 20.04, because when I go to download the release from the Ubuntu Software library, the sound stutters really badly. 
I was following the wiki, but when I got to the "cmake" step, it gave me this error. 
![Screenshot from 2021-01-28 14-24-52](https://user-images.githubusercontent.com/31896923/106188184-a22eaa80-6174-11eb-84ba-f911fbd73466.png)
I'm relatively new to Linux, so any help would be appreciated.

**Comment by isage** [comment]
You missed `..` arter cmake

**Comment by ntninja** [comment]
Run `cmake -Bbuild -H.` from the main project directory. As the error message hints the build directory doesnot contain any CMakeLists file, so CMake doesn't know what its supposed to do there.

**Comment by ntninja** [comment]
@Kittymayor42: Did you install JPEG development headers? (Try `sudo apt install libjpeg-dev`.)

**Comment by Kittymayor42** [comment]
Thanks. I must've missed that one. Fixed it.
