### ISSUE TITLE
Build problem.

### ISSUE THREAD

**Issue by Achaean** [nxengine/nxengine-evo#217]
**Hi!**  :-)

Not sure what it is, so I'm just reporting it.
(Latest stable version, on a Debian oldstable based distro, x64 KDE).

```
>cmake -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread
/usr/include/SDL2
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.28")
CMake Error at CMakeLists.txt:197 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target "nx".


-- Configuring incomplete, errors occurred!
See also "/home/giorgos/TEMPG/nxengine-evo-2.6.5-rc2/build/CMakeFiles/CMakeOutput.log".
See also "/home/giorgos/TEMPG/nxengine-evo-2.6.5-rc2/build/CMakeFiles/CMakeError.log".
 >
```

Logs attached.
**Bye!!!**  :-)
A.

[LOGS.zip](https://github.com/nxengine/nxengine-evo/files/5910710/LOGS.zip)

**Comment by ntninja** [comment]
Weird, this might be due to old CMake doing something unexpected here. Could try replacing `${CMAKE_INSTALL_BINDIR}` with `bin` somewhere around line 197 in “CMakeLists.txt” and see if it helps?

(You are using Linux kernel, right?)

**Comment by Achaean** [comment]
Ehm...Can't find that string at CMakeLists.txt!  :-(

```
>uname -a
Linux PC 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux
>
```

**Comment by Subc2** [comment]
Modifying `CMakeLists.txt` as in commit 8fddbb7b2d0cee842541969a57f250a4066759f0 should fix it.

**Comment by Achaean** [comment]
**Success!!!**  :-)
Latest code, built successfully.

One last question:
How can I run the game?
I can see the executable (inside the build directory) and also the data directory.
No bin directory and trying running the executable, returns an error.

**Comment by ntninja** [comment]
Glad you sorted that out!

> I can see the executable (inside the build directory) and also the data directory.
> No bin directory and trying running the executable, returns an error.

The easiest way to generate complete install is creating an AppImage:

```sh
build-scripts/build-appimage.sh
```

Otherwise you need to extract the non-free assets from the original game and put all of the assets where the game can find them. The following is a quick-and-dirty way for doing this based on the scripts invoked internally during release (make sure you are in the git checkout root directory):

```sh
# Build and install NxEngine-Evo into `build/AppData/usr`
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/AppDir/usr -Bbuild -H.
ninja -Cbuild all install

# Download, extract and add non-free assets to the install
export APP_ID=org.nxengine.nxengine_evo
build-scripts/utils/common.download-extern.sh
build-scripts/utils/common.install-extern.sh build/AppData/usr/share/nxengine build/nxextract
```

We probably should add some CMake rules for the above to make it simpler, though.

**Comment by Achaean** [comment]
**THANKS!!!**
I'll try them.
