### ISSUE TITLE
Moving analog stick on Xbox One controller crashes the game.

### ISSUE THREAD

**Issue by Zanmato27** [nxengine/nxengine-evo#22]
I was trying to remap my controls but this engine instantly crashes the second I move either analog sticks on the Xbox One controller (and presumably Xbox 360 controller as well). This happened on both 32 and 64-bit versions of the Windows NX Engine-EVO.

**Comment by isage** [comment]
Version?
>presumably Xbox 360
No, i use one myself

Anyway, sticks are broken in latest release anyway, please wait a little for next release. (Or build from latest master commit)

**Comment by Zanmato27** [comment]
This happened on both Version 2.5 and 2.4.1.

**Comment by isage** [comment]
Should be fixed in latest release. Please report, if its not.
