### ISSUE TITLE
Korean translation for nxengine-evo

### ISSUE THREAD

**Issue by british-choi** [nxengine/nxengine-evo#222]
I am a Korean developer.
Implemented Korean translation.
Hope to be forked into the nxengine-evo repository.
Thanks.

https://github.com/british-choi/lang_korean

**Comment by isage** [comment]
Hello. There's another one https://github.com/sana2dang/lang_korean

Can you work together on one and I'll pull it into nxevo repository

**Comment by british-choi** [comment]
sana2dang asked me for assistance in implementing a Korean translation.
So the result is british-choi/lang_korean.
sana2dang tested my results, and he was satisfied.
