### ISSUE TITLE
[Switch] v2.6.5 Additional soundtracks not being found

### ISSUE THREAD

**Issue by 16BitWonder** [nxengine/nxengine-evo#223]
I've updated to the new v2.6.5 binary and moved my music directories to the following location and all seem to be unrecognized.
I'm not sure if this is me misinterpreting the new data location from the release notes or if music isn't being looked for correctly by the new binary.
My apologies if it's the former.

```
SD: nxengine/
    L data/
      L Ogg/
      L Ogg11/
      L Ogg17/
      L Ogg_ridic/
```
If it makes a difference, my nro is stored at:
```
SD: switch/0 - Games/NXEngine-Evo-v2.6.5/NXEngine-Evo-v2.6.5.nro
```
Debug log attached below:
[debug.log](https://github.com/nxengine/nxengine-evo/files/6760538/debug.log)

**Comment by isage** [comment]
Hm. But settings and saves do work?

**Comment by 16BitWonder** [comment]
Yes profile.dat, settings.dat and debug.log are all still being read/written to from the NRO directory.

**Comment by isage** [comment]
[NXEngine-Evo-2.6.5.nro.zip](https://github.com/nxengine/nxengine-evo/files/6760571/NXEngine-Evo-2.6.5.nro.zip)
try that one

**Comment by 16BitWonder** [comment]
I think you might've missed a '/' with that build, it's no longer reading my previous settings/profile from the NRO directory and instead produces "nxenginedebug.log", "nxengineprofile.dat" and "nxenginesettings.dat" on the SD card root.

Attached nxenginedebug.log (Still not locating the music directories):
[nxenginedebug.log](https://github.com/nxengine/nxengine-evo/files/6760584/nxenginedebug.log)

**Comment by isage** [comment]
yeah, right.
BTW, what's the best way - use just `data/` in nro dir, or use `/nxengine/data/` on SD?

**Comment by isage** [comment]
[NXEngine-Evo-2.6.5.nro.zip](https://github.com/nxengine/nxengine-evo/files/6760595/NXEngine-Evo-2.6.5.nro.zip)
That one should look in `/nxengine/data/`
But, saves/settings would be in `/nxengine/data/` too. One from releases looks in `data/` in NRO directory (well, atleast it should)

**Comment by 16BitWonder** [comment]
> BTW, what's the best way - use just `data/` in nro dir, or use `/nxengine/data/` on SD?

For switch homebrew I've generally seen contents not stored within NRO romfs either within the same directory as the NRO or in `switch/` (something like `SD:switch/nxengine/`)
I'd lean more towards keeping it in either `SD:nxengine/data/` or `SD:switch/nxengine/data` just so there's consistency about where things are being stored between users.

> That one should look in `/nxengine/data/`
> But, saves/settings would be in `/nxengine/data/` too. One from releases looks in `data/` in NRO directory (well, atleast it should)

This build's generating debug.log, profile.dat and settings.dat in `SD:nxengine/` and reading the music directories from `SD:nxengine/data/` correctly.

[debug.log](https://github.com/nxengine/nxengine-evo/files/6760614/debug.log)

**Comment by isage** [comment]
So, should we use that build then? Or change to `sd:/switch/nxengine/`?

**Comment by 16BitWonder** [comment]
Between `SD:/nxengine/` and `SD:/switch/nxengine/` I'd vote `SD:/switch/nxengine/` to keep it closer to where other homebrew files are generally stored and off of the root.

**Comment by isage** [comment]
Okay, updated switch build in releases to use `/switch/nxengine/` and path description accordingly.

**Comment by 16BitWonder** [comment]
Awesome, tried the new build in releases and it's working flawlessly.
Thank you for looking into this so quickly. ^^
