### ISSUE TITLE
Heavy Presses not falling after falling once & Vsync option?

### ISSUE THREAD

**Issue by PacMax1121** [nxengine/nxengine-evo#224]
Heavy Presses, mostly from Sand Zone can't fall after falling once, resulting in them appearing to floating in thin air.
To reproduce: Shoot a destructible block below the Heavy Press, let it fall to the second destructible block, and shoot the second destructible block, making them, as I said, floating in thin air.

Also, are we gonna get Vsync in a future update? I would be glad if it will happen, because the flickering effects get split in half for mostly appearing in one frame.

EDIT: By Vsync I mean not make the game "60FPS'd" but just fix screen tearing.

**Comment by isage** [comment]
Presses are fixed.

Vsync is, obviously, requires game to run at non-50fps. I think we can atually uncap fps for drawing (which will allow vsunc) while keeping logic/movement running at 50.
Feel free to open separate issue for that.
