### ISSUE TITLE
DCMAKE_INSTALL_PREFIX Not Used In Runtime

### ISSUE THREAD

**Issue by ibrokemypie** [nxengine/nxengine-evo#227]
Trying to update the aur package, the following isntalls the files to the correct locations, however when running nxengine-evo it still looks for data in /usr/local rather than just /usr ``[error] [Font.cpp:81 load]: Error opening font file /usr/local/share/nxengine/data/font_1.fnt`` which obviously fails

```
build() {
  cmake -B build -S "${pkgname}-${_ver}" -DCMAKE_BUILD_TYPE=None \
  		-DCMAKE_INSTALL_PREFIX=/usr -Wno-dev
  make -C build

  cp -r "CaveStory/data/" "${pkgname}-${_ver}/"
  cp "CaveStory/Doukutsu.exe" "${pkgname}-${_ver}/"
  
  cd "${pkgname}-${_ver}"
  ../build/nxextract

}

package() {
	make -C build DESTDIR="$pkgdir" install
}

```

**Comment by xordspar0** [comment]
I think this is fixed, right? The AUR package is working fine now.
