### ISSUE TITLE
Add translation installation instructions

### ISSUE THREAD

**Issue by maxlefou** [nxengine/nxengine-evo#24]
I'm testing the engine so far and it seems to work just right ^^
But I haven't found how to install the additionnal languages on the wiki.

I found by myself. You just need to clone any of the `lang_<language>` repositories and puts its content in the game's folder as `data/lang/<language name>`. For instance, `data/lang/russian`

Would be good to add this on the wiki ^^

**Comment by isage** [comment]
Nah, it's not like that. Languages need to be prebuilt, or you'll get font errors and only menus translated.
I'm using travis for that: https://github.com/nxengine/translations
And all currently built languages are in https://github.com/nxengine/translations/releases
They, in turn, included with the latest release on nxengine-evo. So there's really no need for such instructions for end users.
It does, however, make sense for translators, but build system is linux-only atm.

**Comment by B4rabbas** [comment]
@maxlefou I'm currently correcting your translation, I think I'll finish tonight. If your curious about it look at my repo I've forked yours.

**Comment by maxlefou** [comment]
> @maxlefou I'm currently correcting your translation, I think I'll finish tonight. If you're curious about it look at my repo I've forked yours.

Dude you did a nice work. Damn I was really bad at translating, 10 years ago... I'm pretty glad you kept the essence of the original translation while correcting. ^^
There's some minor things you can do before you pull request tho:
- in `Oside.txt`, line 56: `au coeur des montagnes` and not `au cour`
- For the rest, I haven't tried, but is the real `œ` shows ok in game? Because if yes, why not using `œ` and `Œ` instead of `oe` ;)
Except for these details, you should be ready for the pull request, Everything is valid for me. :)

**Comment by isage** [comment]
> is the real œ shows ok in game
It should with fonts from Polish translation.
I'll update font metadata for French to include full Latin extended/supplement charsets.

**Comment by isage** [comment]
BTW, i've updated metadata in lang-french so now  `œ` and `Œ` should work

**Comment by B4rabbas** [comment]
I'll update the translation tonight or tomorrow, I'm not sure it'll be flawless cause it need test, but should be nice, close to a commercial localisation.

**Comment by isage** [comment]
Oh, nice. I'm preparing new release, so i'll wait till your translation
merged

**Comment by isage** [comment]
@B4rabbas any update on this?

**Comment by maxlefou** [comment]
Since it's been a long while, I still can merge his corrections already done (adding the œ while i'm at it) with mines... I'll also add him in the credits file, of course ^^

**Comment by maxlefou** [comment]
and btw, closing this cuz, well... :p
