### ISSUE TITLE
Cave Story Plus "mods"?

### ISSUE THREAD

**Issue by MaddTheSane** [nxengine/nxengine-evo#247]
I noticed that the Mac version of Cave Story+ has a `mods.txt` file that lists different game modes. Trying to use the "Machine Gun Challenge" mode (with a custom-made json) results in a new game with, well...
<img width="641" alt="Screen Shot 2021-10-21 at 3 14 59 PM" src="https://user-images.githubusercontent.com/719492/138357839-3eecd7d8-f4b1-4fd7-8597-12bf3f8d3a90.png">

Could the difference in directory structure that Cave Story+ uses, or is the mod support not mature enough?

**Comment by isage** [comment]
nxevo doesn't support assets nor mods from cs+. and won't.
