### ISSUE TITLE
How can I actually run nxengine-evo with multiple languages?

### ISSUE THREAD

**Issue by crocket** [nxengine/nxengine-evo#249]
The instruction on https://github.com/nxengine/nxengine-evo/wiki/Running is incomplete.

* Somehow, it always assumes that everything is in /usr/share/nxengine. Can it run somewhere else?
* I want to run Cave Story in multiple languages including english and japanese.

**Comment by isage** [comment]
Languages are included, you don't need to have different cave story versions (see buildscripts for appimage, for example)
Yes, it assumes that data is in /usr/share/nxengine. 
You can build it with PORTABLE (assumes that data is in same folder as binary) or with custom DATADIR.
Or just use appimage/snap, it includes all data.

**Comment by crocket** [comment]
Figuring out the necessary components to build a gentoo linux package for nxengine-evo from flakpak build script was quite challenging without the right instructions.

I needed

* https://github.com/nxengine/nxengine-evo/archive/v${PV}.tar.gz
* https://www.cavestory.org/downloads/cavestoryen.zip
* https://github.com/nxengine/translations/releases/download/v1.14/all.zip

After building nxengine-evo, I copied cavestoryen.zip/data, cavestoryen.zip/Doukutsu.exe, and all.zip/data to nxengine-evo source directory and executed `make install`.

**Comment by xordspar0** [comment]
See also for reference the [Arch AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nxengine-evo) and my personal [Alpine package](https://git.sr.ht/~xordspar0/packages/tree/master/item/aports/nxengine-evo/APKBUILD). Now that you mention it, those versions don't include multiple languages. I will probably update them to do that.

**Comment by crocket** [comment]
I think this issue is prematurely closed. The setup instructions should be documented somewhere.

**Comment by isage** [comment]
#252
