### ISSUE TITLE
Support for accents and symbols

### ISSUE THREAD

**Issue by maxlefou** [nxengine/nxengine-evo#25]
NX Engine not supporting accents always been an issue. But nobody really cared about it since there's no language selection menu or anything, making the problem just isolated for some few people :p 

But since NX Enging Evo features the language choosing feature, it would be good to add support for accents such as `é` `è` `à` `ù` `ç` and so on.

So far the french language sees its accents completely truncated (`Français` being `Franais` for instance) and flooding the console with errors. :p

**Comment by isage** [comment]
It does, actually, it just needs a correct font. Here's prebuilt french translation with right font: https://transfer.sh/2fyOI/french.zip

**Comment by isage** [comment]
I've released new versions on langpack and nxengine-evo, now with Français included.
