### ISSUE TITLE
Does this support Cave Story+ ?  Are there any differences in that version?

### ISSUE THREAD

**Issue by sofakng** [nxengine/nxengine-evo#254]
I've purchased Cave Story+ on Steam but it doesn't work on MacOS due to 32-bit incompatibility.

Can I use those files with this engine?

Are there any differences in "Cave Story+" versus that base games this does support?

**Comment by xordspar0** [comment]
Nope, it doesn't support Cave Story+. But it does run on a ton of platforms. Personally, I like nxengine-evo a lot better than Cave Story+. If you haven't tried it I would highly recommend it.

**Comment by sofakng** [comment]
Thanks for the response.

What's the difference between Cave Story+ and the other versions of the game?

**Comment by xordspar0** [comment]
Cave Story+ has new, redrawn art that is higher resolution. It comes with multiple arranged soundtracks in addition to the original one (NXEngine-evo does support the extra soundtracks). The game speed is increased by 20%. It comes with a couple extra time attack levels. It has a new translation.

A few of the changes are nice, like supporting multiple save slots. But NXEngine also added that and other features that are definitely improvements. Most of the changes are just different, not better. Increasing the game speed and doing the translation over again did not make Cave Story+ better in my opinion.

**Comment by isage** [comment]
#218
