### ISSUE TITLE
Defeating Sacred Grounds Saves Time as 0'0"

### ISSUE THREAD

**Issue by hjk321** [nxengine/nxengine-evo#255]
I just beat the best ending on latest release without the timer item and the time was saved as 0'0", giving me the Sue title screen. No mods. Platform is macOS.

<img width="1440" alt="TitleScreen" src="https://user-images.githubusercontent.com/37224753/141665178-c68afb2d-542d-4a50-8f67-0e52d895f403.png">

**Comment by hjk321** [comment]
So I'm assuming the project is abandoned at this point?

**Comment by xordspar0** [comment]
For anyone who wants to test 290.rec in the future, I extracted nxengine-evo's niku.cpp to a utility here:

https://git.sr.ht/~xordspar0/personal/tree/master/item/c/niku.c
<blockquote><pre>USAGE:
	niku save &lt;number&gt;
	niku load
</pre></blockquote>
