### ISSUE TITLE
save file

### ISSUE THREAD

**Issue by Exarkuniv** [nxengine/nxengine-evo#259]
not really a issue, just wondering where the save files are located when it is installed.

we are trying to see where they go, and if they are be told to save somewhere else.

**Comment by Exarkuniv** [comment]
very cool, thanks again. 
ill update once i do a little testing

**Comment by Exarkuniv** [comment]
@xordspar0 
im still learning on how RetroPie uses its own fuctions. so useing ``env`` is not needed.

i do have other questions. on the menu there is a option for Mods. how does that work?

**Comment by isage** [comment]
There's sample mod included with https://github.com/nxengine/nxengine-evo/releases/tag/v2.6.5 release.
Basically, mods just overwrite datafiles

**Comment by Exarkuniv** [comment]
thank you @isage 
my last question.

with retropie most binarys are installed to the ``opt`` folder. we have figured out how to make this work for nxengine-evo with the freeware version of cavestory

is there a way to have ``nxengine`` look for the data files else where. so that way we can have the data files easily replaceable by the user? so they can install other versions?

**Comment by isage** [comment]
Same path as saves. It's one of the places nxevo looks for data

**Comment by isage** [comment]
You can also define DATADIR when building for a custom one

**Comment by Exarkuniv** [comment]
thank you i think thats what im looking for.  
would this work?

``cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev -DPORTABLE=On -DATADIR=romdir/ports/CaveStory ``

**Comment by isage** [comment]
`-DDATADIR=...`, otherwise, yep

**Comment by Exarkuniv** [comment]
so i have this `` cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev -DDATADIR="$romdir/ports/CaveStory" -DPORTABLE=On ..
`` 
and i have the ``data`` folder in ``ports/CaveStory``
when i run ``nxengine`` 
i get this  
``
[21:45:59.878] [error] [Font.cpp:81 load]: Error opening font file /opt/retropie/ports/nxengine-evo/data/font_1.fnt
[21:45:59.878] [critical] [main.cpp:58 fatal]: fatal: 'Failed to initialize graphics.'
``
are there some files that need to be `` /opt/retropie/ports/nxengine-evo/data`` or did i mess something up?

**Comment by isage** [comment]
Can you run `make clean` and then `VERBOSE=1 make` and post output?

**Comment by s1eve-mcdichae1** [comment]
> Same path as saves. It's one of the places nxevo looks for data

What happens if there's data found in more than one place? Can we build with -DPORTABLE and -DDATADIR and then put the freeware data in a read-only dir with the binary, but put mods in a user-writable `$datadir`? Or does it just treat the first one it finds as the only one?

**Comment by s1eve-mcdichae1** [comment]
> Can you run `make clean` and then `VERBOSE=1 make` and post output?

Almost looks like `--DDATADIR` is not being honored?:

```
pi@retropie:~/temp/nxe/build $ cmake -DCMAKE_BUILD_TYPE=Release -DDATADIR="/home/pi/RetroPie/roms/ports/cavestory" ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread  
-- Found SDL2_mixer: /usr/lib/arm-linux-gnueabihf/libSDL2_mixer.so (found version "2.0.4")
-- Found SDL2_image: /usr/lib/arm-linux-gnueabihf/libSDL2_image.so (found version "2.0.4")
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36") 
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so (found version "62") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DATADIR


-- Build files have been written to: /home/pi/temp/nxe/build
```

...at the end there, where it says "manually-specified variables were not used."

Then when I move the `data` dir *to* the `$datadir` and run the binary, it's still looking in `/usr/local/share`:

```
pi@retropie:~/temp/nxe/build $ cp -r ~/nxport/data/ ~/RetroPie/roms/ports/cavestory/
pi@retropie:~/temp/nxe/build $ ./nxengine-evo 
[22:50:52.795] [info] [input.cpp:110 input_init]: Opened Joystick 0
[22:50:52.855] [info] [input.cpp:111 input_init]: Name: Logitech Gamepad F710
[22:50:52.855] [info] [input.cpp:112 input_init]: Number of Axes: 6
[22:50:52.855] [info] [input.cpp:113 input_init]: Number of Buttons: 11
[22:50:52.855] [info] [input.cpp:114 input_init]: Number of Balls: 0
[22:50:52.855] [info] [settings.cpp:28 tryload]: Loading settings...
[22:50:52.995] [info] [Renderer.cpp:134 initVideo]: Renderer::initVideo: using: opengl renderer
[22:50:52.995] [error] [Font.cpp:81 load]: Error opening font file /usr/local/share/nxengine/data/font_1.fnt
[22:50:52.995] [critical] [main.cpp:58 fatal]: fatal: 'Failed to initialize graphics.'
```

...and when @Exarkuniv built with `-DPORTABLE=On -DDATADIR=<$data dir>` then it was looking in `/opt/retropie/ports` (where the binary lives) but still not in the specified `<$data dir>`.

`VERBOSE=1 make` log (54 KB): https://pastebin.com/D5JLzPcC

**Comment by isage** [comment]
Oh, right, my bad, that won't work.
CFLAGS='-DDATADIR="..."' CXXFLAGS='-DDATADIR="..."' cmake ...

That should

**Comment by s1eve-mcdichae1** [comment]
Does it work with `-DPORTABLE` or is it one or the other?

**Comment by isage** [comment]
It requires -DPORTABLE=ON

**Comment by s1eve-mcdichae1** [comment]
It requires. Okay. So:

    CFLAGS='-DDATADIR="/path"' CXXFLAGS='-DDATADIR="/path"' cmake -DCMAKE_BUILD_TYPE=Release -DPORTABLE=On ..

...? And then where does the data (and the "`data`" dir) actually go in relation to `/path`? Are we looking at

    /path/data/<data files>
    
Or

    /path/<data files>
    
Or

    /path/nxengine/data/<data files>
    
...or something else?

**Comment by isage** [comment]
First one

**Comment by s1eve-mcdichae1** [comment]
Great, thanks! Imma start the build & turn in for the night, will test it out tomorrow.

**Comment by s1eve-mcdichae1** [comment]
Ah well, I'm back sooner than expected:

```
pi@retropie:~/temp/nxe/build $ CFLAGS='-DDATADIR="/home/pi/RetroPie/roms/ports/cavestory"' CXXFLAGS='-DDATADIR="/home/pi/RetroPie/roms/ports/cavestory"' cmake -DCMAKE_BUILD_TYPE=Release -DPORTABLE=On ..
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread  
-- Found SDL2_mixer: /usr/lib/arm-linux-gnueabihf/libSDL2_mixer.so (found version "2.0.4")
-- Found SDL2_image: /usr/lib/arm-linux-gnueabihf/libSDL2_image.so (found version "2.0.4")
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36") 
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so (found version "62") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/temp/nxe/build
pi@retropie:~/temp/nxe/build $ nohup make &
[1] 28293
pi@retropie:~/temp/nxe/build $ nohup: ignoring input and appending output to 'nohup.out'

```

Minutes later: 



```
1]+  Exit 2                  nohup make  (wd: ~/temp/nxe/build)
(wd now: ~/RetroPie/roms/ports/CaveStory)
pi@retropie:~/RetroPie/roms/ports/CaveStory $ cd
pi@retropie:~ $ cd temp/nxe/build
pi@retropie:~/temp/nxe/build $ wc -l nohup.out 
58 nohup.out
pi@retropie:~/temp/nxe/build $ cat nohup.out 
Scanning dependencies of target extract
[  0%] Building CXX object CMakeFiles/extract.dir/src/extract/crc.cpp.o
[  1%] Building CXX object CMakeFiles/extract.dir/src/extract/extractfiles.cpp.o
[  2%] Building CXX object CMakeFiles/extract.dir/src/extract/extractpxt.cpp.o
[  2%] Building CXX object CMakeFiles/extract.dir/src/extract/extractstages.cpp.o
[  3%] Building CXX object CMakeFiles/extract.dir/src/extract/main.cpp.o
[  4%] Building CXX object CMakeFiles/extract.dir/src/common/misc.cpp.o
[  4%] Building CXX object CMakeFiles/extract.dir/src/Utils/Logger.cpp.o
[  5%] Building CXX object CMakeFiles/extract.dir/src/stagedata.cpp.o
[  6%] Linking CXX executable nxextract
[  6%] Built target extract
Scanning dependencies of target nx
[  7%] Building CXX object CMakeFiles/nx.dir/src/ObjManager.cpp.o[  7%] Building CXX object CMakeFiles/nx.dir/src/ResourceManager.cpp.o
/home/pi/temp/nxe/src/ResourceManager.cpp: In member function ‘std::__cxx11::string ResourceManager::getPath(const string&, bool)’:
<command-line>: error: expected primary-expression before ‘/’ token
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘home’ was not declared in this scope
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: note: suggested alternative: ‘time’
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘pi’ was not declared in this scope
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘RetroPie’ was not declared in this scope
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘roms’ was not declared in this scope
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: note: suggested alternative: ‘mods’
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘ports’ was not declared in this scope
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: note: suggested alternative: ‘puts’
/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
<command-line>: error: ‘cavestory’ was not declared in this scope/home/pi/temp/nxe/src/ResourceManager.cpp:123:23: note: in expansion of macro ‘DATADIR’
     std::string _data(DATADIR);
                       ^~~~~~~
make[2]: *** [CMakeFiles/nx.dir/build.make:76: CMakeFiles/nx.dir/src/ResourceManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/nx.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by isage** [comment]
Right, you need to additionally quote path
`CFLAGS='-DDATADIR="\"/home/pi/RetroPie/roms/ports/cavestory\""'`

**Comment by s1eve-mcdichae1** [comment]
> Right, you need to additionally quote path
> `CFLAGS='-DDATADIR="\"/home/pi/RetroPie/roms/ports/cavestory\""'`

So close. Needed another slash after `cavestory` as in @Exarkuniv's comment above, then it looks to have worked.

> First one

It was the second, actually. It's looking for `.../cavestory/font_1.fnt`, not `.../cavestory/data/font_1.fnt`

> Can we ... put the freeware data in a read-only dir with the binary, but put mods in a user-writable $datadir?

Looks like this isn't going to work. With the $datadir set this way, including `-DPORTABLE=On`, it no longer works *as* portable. It doesn't work with data files next to the binary, if that's not also where `$datadir` is specified. It just looks in `$datadir` and if it doesn't find the first font file there, it quits with the error. @isage is that right, or is there something else we can do?

**Comment by Exarkuniv** [comment]
from how im taking what @isage said a few posts above ``Basically, mods just overwrite datafiles`` 

but i have mods working just fine with my setup now and i can still pick the normal cavestory. 
as far as i know how the ports work or at least how i have done mine in the past it is working as i would like it to.

**Comment by isage** [comment]
@s1eve-mcdichae1 it checks <savedir>/data, then DATADIR

**Comment by s1eve-mcdichae1** [comment]
@isage thanks, I think we can work with this.

@Exarkuniv yeah, it looks like the game data will just have to live in `$romdir/$datadir` since we need to be able to put the mods there. I have some additional thoughts, I'll post them to your project once I make them make sense :)

**Comment by Exarkuniv** [comment]
@s1eve-mcdichae1 sounds good, im going to close this issue since its all working, 
anything new we make a new one

**Comment by s1eve-mcdichae1** [comment]
> Right, you need to additionally quote path
> `CFLAGS='-DDATADIR="\"/home/pi/RetroPie/roms/ports/cavestory\""'`

The actual path that I am using is now:

    /home/pi/RetroPie/roms/ports/CaveStory/nxengine-evo/data/

In our install script, though, some of this is handled by vars, so in the script it looks like:

    $romdir/ports/CaveStory/$md_id/data/

This isn't expanding right when I put it in the script as:

    CFLAGS='-DDATADIR="\"$romdir/ports/CaveStory/$md_id/data/\""' CXXFLAGS='-DDATADIR="\"$romdir/ports/CaveStory/$md_id/data/\""' cmake -DCMAKE_BUILD_TYPE=Release -DPORTABLE=On ..

It builds alright, but then when I run it, says can't find file in "`omdir/ports/CaveStory/d_id/data/`."

I know it has to do with "how bash expands variables" re: single- and double-quotes, but I don't know quite what to do with that information. I tried swapping them which didn't work, nor did using double-quotes exclusively (escaping the existing un-escaped doubles that were now inside the outer ones). It didn't even build, with those.

Got any hints?
