### ISSUE TITLE
Questions about dependencies.

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [nxengine/nxengine-evo#261]
(Apologies for the probably naive questions...I'm self-taught which means there's a lot I've missed on the way to where I am.)

I'm trying to minimize the number of dependency packages we need to install in our RetroPie script.

**TheWiki** says, in *Linux*:

> sudo apt install build-essential libpng-dev libjpeg-dev make cmake cmake-data git libsdl2-dev libsdl2-doc libsdl2-gfx-dev libsdl2-gfx-doc libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev

A couple of these are covered by our distro, and surely the `-docs` aren't really necessary right? When I build the makefikes with `cmake` I see the report mentions a few of the rest:

```
--Found SDL2: /usr/lib/arm-linux-gnueabihf/libSDL2main.a;/usr/lib/arm-linux-gnueabihf/libSDL2.so;-lpthread  
-- Found SDL2_mixer: /usr/lib/arm-linux-gnueabihf/libSDL2_mixer.so (found version "2.0.4")
-- Found SDL2_image: /usr/lib/arm-linux-gnueabihf/libSDL2_image.so (found version "2.0.4")
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36") 
-- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so (found version "62") 
```

It doesn't say anything about `libsdl2-gfx-dev libsdl2-net-dev libsdl2-ttf-dev`. Are these really necessary? I've built and run this without ever installing `libsdl2-gfx-dev`, for example; I did it again *with* the package and the binaries were identical as reported by `diff` so unless it makes a difference at runtime I don't think this one is needed? (Or, is this dep just being filled by something else I have on my system, but *something* is still needed regardless? I do see `libsdl2-gfx-1.0-0` installed as a dep of something else on my system, for example.)

I didn't test anything without the `ttf` and `net` packages because they *were* already on my system from other installations in the past, I only ask about them because I didn't see them mentioned in the build report.

However it does also mention `ZLIB`, which I do have both `zlib1g` and `zlib1g-dev` on my system already. Do I need to make one of these a dep for the install, as well?

**Comment by isage** [comment]
`libsdl2-doc libsdl2-gfx-dev libsdl2-gfx-doc libsdl2-net-dev libsdl2-ttf-dev` aren't needed. I'll fix wiki.
zlib-dev is usually pulled in by libpng-dev, but you can add it to deps, yeah

**Comment by s1eve-mcdichae1** [comment]
Oh yeah I see it is dep of libpng-dev so I don't need it explicit.

Thanks!
