### ISSUE TITLE
Automatically detect invalid soundcache.

### ISSUE THREAD

**Issue by nlburgin** [nxengine/nxengine-evo#27]
After building from source, I had an issue with sound effects not playing.

I spent about an hour trying to figure out what was wrong, and eventually solved the problem by deleting the file `/home/neil/.local/share/nxengine/nxengine-evo/sndcache.pcm`, forcing the game to regenerate it, and then sound effects played just fine.

After I realized I should probably submit a bug report for this, I rescued the invalid cache from my trash can, and included it here. I don't know how it occurred, but it would be nice if future releases could automatically detect and fix this problem.

[sndcache.pcm.zip](https://github.com/nxengine/nxengine-evo/files/1745649/sndcache.pcm.zip)

**Comment by isage** [comment]
I'll probably just remove sndcache (along with drum.pcm) altogether. It doesn't take that much time to regenerate sounds.

**Comment by nlburgin** [comment]
That sounds reasonable to me.

**Comment by isage** [comment]
Fixed in https://github.com/nxengine/nxengine-evo/commit/d0fc90f1d25824d83829f7d3d3f1fefb0e3ab4f6
