### ISSUE TITLE
Where is the widescreen option?

### ISSUE THREAD

**Issue by nicosensei** [nxengine/nxengine-evo#270]
Hi,

I've compiled from source and I'm unable to select my resolution (1280x720). I can't see anything in the options menu related to widescreen. Is there something specific at build time to enable widescreen support?

**Comment by isage** [comment]
There's no widescreen "option".
Available resolutions are detected based on what your system supports and that list https://github.com/nxengine/nxengine-evo/blob/master/src/graphics/Renderer.cpp#L209
1280x720 isn't one of them

**Comment by nicosensei** [comment]
Hi, wow thanks for a lightspeed answer :-)

I'll try adding my resolution and recompile.

**Comment by isage** [comment]
Problem is, it requires something like base resolution of 512x288 with scale factor of 2.5, but float scale factors aren't supported yet

**Comment by nicosensei** [comment]
Actually works like a charm. I'll do a pull request.

**Comment by isage** [comment]
640 might be a little too much width, that should be tested with curly in core room and with toroko after boss battles with normal ending.

**Comment by nicosensei** [comment]
Ok, how can I test that?

Alternatively, what about setting for a 4x scaling with a 320x180 rendering
resolution? Seems low to me.

Or 427x240 with 3x, however that is approximate for the width.

**Comment by isage** [comment]
320x180 is too low. 427x240 might work.
As for testing - after boss battles in normal ending toroko runs left and disappears. She shouldn't disappear while on screen, if she does - that means screen width is too high

**Comment by nicosensei** [comment]
427x240 works better on smaller screens. I tested on my GPD Win, it looks much better, 640x300 is too zoomed out.

Closing the issue, PR is on its way. Thanks a lot for your help!
