### ISSUE TITLE
Bring the Vita port to VitaDB to make it easier to find the game

### ISSUE THREAD

**Issue by Idah00** [nxengine/nxengine-evo#278]
I realized that nxengine-evo is not available on VitaDB, there is now an homebrew app called VitaDB Downloader to install and update homebrews from vitaDB and it would make things very sleek if we could install and update the game from there.

Do you guys mind bringing the game over there?

Here is the link to the service:
https://vitadb.rinnegatamante.it/#/

**Comment by isage** [comment]
You can notice that there's lots of homebrew (be that separate ports or better/updated versions) missing from vitadb.
The reason is simple: Rinne doesn't list apps from people he doesn't like.
Nothing we can do about that.
