### ISSUE TITLE
Fix compiling with GCC 13

### ISSUE THREAD

**Issue by musuruan** [nxengine/nxengine-evo#280]
Hi. 
I had to include in `<cstdint>` in  `src/siflib/sectStringArray.h` to be able to compile nxengine-evo 2.6.5-1 under GCC 13:
https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

Here's a patch to fix this issue:

```
diff -durN nxengine-evo-2.6.5-1.orig/src/siflib/sectStringArray.h nxengine-evo-2.6.5-1/src/siflib/sectStringArray.h
--- nxengine-evo-2.6.5-1.orig/src/siflib/sectStringArray.h      2021-07-08 12:48:08.000000000 +0200
+++ nxengine-evo-2.6.5-1/src/siflib/sectStringArray.h   2023-04-01 21:03:38.553686500 +0200
@@ -1,6 +1,7 @@
 
 #ifndef _SECT_STRINGARRAY_H
 #define _SECT_STRINGARRAY_H
+#include <cstdint>
 #include <string>
 #include <vector>
```

**Comment by xordspar0** [comment]
I can't get ahold of a copy of GCC 13 to test this. I tried compiling from source but I haven't yet been successful.

**Comment by musuruan** [comment]
Use one of the distributions that already has GCC 13, such as Fedora Rawhide, openSUSE Tumbleweed, ArchLinux, Gentoo, etc.

**Comment by isage** [comment]
Fixed
