### ISSUE TITLE
You shouldn't be able to stand on Igor in Balcony

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#30]
This has something to do with either repel, or collision check. In NXEngine 1.0.0.4 it works as intended (although rabid mimiga also deals damage sometimes, which it shouldn't)

**Comment by nlburgin** [comment]
Can confirm that it is now consistent. 

You can no longer stand on Igor, and can only safely stand on the smaller rabid mimiga when it's not in the middle of its lunge attack (which is also consistent with the original).
