### ISSUE TITLE
Bluetooth gamepad support

### ISSUE THREAD

**Issue by billywade** [nxengine/nxengine-evo#34]
I'm trying to set up my Bluetooth gamepad with the game, but no luck. Bluez and bluez-extra can use it for other systems, but I'm not sure how to go about implementing it here, or how to set it up if it already exists. 

I'm running Manjaro x64, and the gamepad is a Sixaxis 3, if that helps. I build nx-evo from source, so if it's in a recent build I'd be happy to upgrade and set up from there.

**Comment by isage** [comment]
It shouldn't matter to the engine (or to the SDL2 for that matter) if it's bluetooth or not.
So, the game doesn't react when you try to bind keys in settings, right? Does it work with other games?
Can you past first few lines from your ~/.local/share/nxengine/nxengine-evo/debug.log (up until "Loading settings..." if that's not a first line)?
Also, how does gamepad present itself in /dev ?

**Comment by billywade** [comment]
Okay, for some reason, it'll let me apply controls while the controller is plugged, but not in wireless, but will accept the controls while wireless. It's weird, but not broken, so this is resolved.
