### ISSUE TITLE
Most widescreen resolutions automatically disabled

### ISSUE THREAD

**Issue by billywade** [nxengine/nxengine-evo#35]
Hey, I'm having a little trouble getting widescreen to work. When I run the `nx-evo` command and try to change the resolution, it only offers a few options, none of which are close to my actual resolution of 1360x768. However, when Iook at the output, something sticks out to me:
```
Setting pause: type 9 param 0
DW: 1360, DH: 768
Disabling 1280x1024
Disabling 1600x1200
Disabling 1366x768
Disabling 1440x900
Disabling 1920x1080
DW: 1360, DH: 768
Disabling 1280x1024
Disabling 1600x1200
Disabling 1366x768
Disabling 1440x900
Disabling 1920x1080
Setting pause: type 0 param 0
Writing settings...
Setting tick function to type 1 param 0
```
So it looks like nx-evo recognizes my resolution, but why are all of these display options taken off the table? Is it because they exceed my current resolution? Is there any way to get at least 1366x768, since it's only a few pixels off of my current resolution?

Thanks!

**Comment by isage** [comment]
Yep. it disables resolutions that exceed current desktop resolution.
I've added 1360x768 in https://github.com/nxengine/nxengine-evo/commit/08116bffe8d3c3b06fb0e58dc397858f2f33d91c

**Comment by billywade** [comment]
Thanks! I'll pull and build in a few.
