### ISSUE TITLE
Out of Bounds tiling for widescreen

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#36]
Enhancement request:
Extended looping tile patterns rendered out of bounds in the many non-scrolling one-screen maps, for widescreen aspect ratios.

Proposed solution:
Add an optional, tiny new piece of map-specific metadata (a file sharing the map's name, in a different folder perhaps?) containing the tile ID(s) to draw out-of-bounds around the map, accepting either a single tile (for those "off-black" indoor rooms) or a 2x2 square of tiles (for the cave tilesets) to render outside of the map in place of the background.

Following that, it would be possible to consider allowing the camera to scroll a few tiles out of bounds in widescreen aspect ratios even in larger areas, so that the exit doors don't seem extrordinarily close to one side of the screen compared to the 4:3 view of the map. But, that's a discussion for another issue thread.

**Comment by isage** [comment]
Could you mock-up some images of how this should look?

**Comment by Yukitty** [comment]
Sure thing!
This is what Start Point looks like "by default", with no out-of-bounds metadata.
![start_point_oob](https://user-images.githubusercontent.com/8621403/42205711-ccbb20ac-7e6a-11e8-9113-9eb2fca03688.png)

Let's assume the new special metadata for this map is located in a file named `"data/StageMeta/Start.json"`
If we write something like `{ "out-of-bounds": [ 32, 33, 48, 49 ] }` there, it should render those tiles from PrtCave aligned around the borders of the map like this:
![start_point_oobmeta](https://user-images.githubusercontent.com/8621403/42205954-787f98fa-7e6b-11e8-89e2-38ed150761db.png)

For other maps, like the little room Kazuma starts out in, only one tile is required. So if instead the metadata says `{ "out-of-bounds": [ 48 ] }` and the map's tileset is PrtStore, it should be able to render the map like this:
![kazuma_oob](https://user-images.githubusercontent.com/8621403/42206333-6c5d901c-7e6c-11e8-9e53-2b05969ebe4b.png)

Currently I am working on the assumption that these two use cases, supplying only 1 tile or 4 which form a square, are the only relevant ones to the unmodded game. (Is there a map which has a foreground tile pattern of two wide and one tall..?)

**Comment by isage** [comment]
Sure, that looks reasonable and doable.
I'll check for other maps, but we can adjust metadata format accordingly if needed.

**Comment by Yukitty** [comment]
I've already done the JSON processing myself, although that's probably the easy/fun part. :3
https://github.com/Yukitty/nxengine-evo/commits/patch-oob-tiles

**Comment by isage** [comment]
Oh, that's nice. And i'm perfectly okay with json (in fact, i'm slowly working on converting other binary files to json, right after i finish support for bidi/rtl languages).
Looking forward for full pull-request then!

**Comment by isage** [comment]
Implemented in #37

**Comment by isage** [comment]
Hm. Looks like there are problems on resolutions, that have scale factor set to 3.
![screenshot017](https://user-images.githubusercontent.com/273697/42244648-874e624a-7f1e-11e8-9f56-11c8d66083a8.png)

**Comment by isage** [comment]
I think the proper way would be to start from map edges and draw outwards, until screen edge, rather than starting from screen edges and drawing towards map.

**Comment by Yukitty** [comment]
Yeah, not only that, but I'm noticing problems with earthquakes as well. 😥 Sorry for the bum patch.

**Comment by Yukitty** [comment]
#39 works for me, hoping it'll fix everything for you as well. 🙇

**Comment by isage** [comment]
Yup, works for me too.

**Comment by isage** [comment]
Hm. I'm not sure Ring1 (misery battle in throne room) should have oob tiles, because it looks weird after battle.

**Comment by Yukitty** [comment]
You're right, at the resolution I was playing on it was fine, but the aspect ratios with even-more vertical space don't handle it well at all. 😞
