### ISSUE TITLE
Pooh Black death anim.

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#41]
When I killed Pooh Black, they were midair, vanished immediately (emitting a console error `error << FindObjectByID2: ID2 0300 found: type OBJ_POOH_BLACK(160); coords: (100, 64) >>`), spewwed bubbles continuously upwards for an _awkwardly_ long time (while invisible), and continued to do so long after the sound effects ended. I'm pretty sure they're missing a "disappearing" animation, since if I recall they normally "die" by vaporizing from the bottom-up.

Here's a handy savegame.
[profile-pooh_black.zip](https://github.com/nxengine/nxengine-evo/files/2161443/profile-pooh_black.zip)

**Comment by Yukitty** [comment]
Oh? Weird. I'll try again on my end. o.o
It might be a Linux thing, maybe? Probably not, but...

**Comment by isage** [comment]
Nah, linux is my primary os.
If it's reproducible on your end, then what compiler (gcc/clang) are you
using, and what version?
There could be some initialized variable somewhere, but my sleepy eyes
can't find anything suspicious.

**Comment by Yukitty** [comment]
I've managed to replicate it, and it's very specific:
It only happens if you manage to kill him mid-air while he's trying to land on you.

I've made a video demonstrating it.

**Comment by Yukitty** [comment]
Upon closer inspection, it looks like the problem here is actually that Pooh Black continues falling. Right through the floor. Switching to the death animation doesn't stop it from falling.
