### ISSUE TITLE
Plantation pipe tile

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#44]
![screenshot from 2018-07-04 00-40-04](https://user-images.githubusercontent.com/8621403/42258748-e7110170-7f22-11e8-9604-972f85ce4f3b.png)
I believe either this tile (which I am standing in) or the script attached to the connecting side of it, is supposed to shoot you out vertically, at least enough to catch the current and... not be standing in the pipe.

Maybe it doesn't teleport you to the correct position something..?

**Comment by isage** [comment]
Should be fixed now.
