### ISSUE TITLE
1:1 background rendering isn't resolution-safe

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#47]
![screenshot from 2018-07-04 03-33-29](https://user-images.githubusercontent.com/8621403/42269075-caf6245a-7f42-11e8-9fc4-d74c0c15dbbd.png)
My out-of-bounds tile efforts can only mask over so much, heh...

**Comment by isage** [comment]
There are also problems on other hell sub-levels, ugh.
Maybe we should just draw most backgrounds fullscreen?

**Comment by Yukitty** [comment]
The only reason not to draw most/all backgrounds over the full screen area is for the sake of ensuring the background doesn't appear to "move" between resolution changes. And that's probably easily solved by wildly bashing the math repeatedly until it works right. This is how I solve all my problems, you might have noticed. :V

**Comment by isage** [comment]
Well, we could draw bg on fullscreen, and still adjust its position.

**Comment by isage** [comment]
Hell should be fixed now.
I'm not sure about adjusting BGs between resolution changes. It's a very rare use case (well, usually you adjust resolution prior to playing and leave it as is forever)

**Comment by Yukitty** [comment]
That works. Since all the backdrops in Cave Story are either indistinct tiling or parallax clouds, there's no reason to worry about getting the texture alignment exact anyway. I would be foolish to say otherwise.
