### ISSUE TITLE
Hell statues don't transform

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#48]
![screenshot from 2018-07-04 03-42-14](https://user-images.githubusercontent.com/8621403/42269378-9db4c392-7f43-11e8-92e7-c57529fb7cb1.png)
While doing a run through Hell, if you detour into the Statue Room (where statues of previous Kings are kept), you can destroy them for a big Exp triangle, and they'll turn into smaller statues of the heroes instead.

Unfortunately, only the Curly statue appears. The ones for King, Toroko, and Quote just vanish instead.

**Comment by isage** [comment]
That's... strange. I remember fixing statue plaques, and they worked fine
then. Ugh.

**Comment by Yukitty** [comment]
[statues.webm.gz](https://github.com/nxengine/nxengine-evo/files/2164278/statues.webm.gz)
This time even Curly didn't appear, and I have no idea why. I am so confused. Is there something I'm missing? @@;

**Comment by isage** [comment]
Oh. Rocket launcher was the key to stable reproducing this.

**Comment by Yukitty** [comment]
Huh. Who would've guessed statues just didn't like being blown to smithereens. 😂

**Comment by isage** [comment]
Should work now.
