### ISSUE TITLE
Main Artery handles alt. resolutions particularly poorly

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#49]
![screenshot from 2018-07-04 04-56-50](https://user-images.githubusercontent.com/8621403/42270671-0f3edd92-7f47-11e8-9ebd-43d8056d8e55.png)
![screenshot from 2018-07-04 04-57-44](https://user-images.githubusercontent.com/8621403/42270682-164b22ee-7f47-11e8-9012-3b4ff852f40a.png)

I do believe this is special-case enough to warrent its own issue, considering the wacky autoscrolling walls and background not used anywhere else.

**Comment by Yukitty** [comment]
Also the background here should probably respect pause menus, since it's supposed to be synched with the flying "foreground" tiles...

**Comment by isage** [comment]
Okay, there are lot of problems in main artery:
1) Ikachan easter-egg tiles are drawn (this should be fixed in latest commit)
2) Background misaligned. 
3) Background doesn't respect pause
4) Ironhead disappears/appears too early on the left side

**Comment by isage** [comment]
4 should be fixed now.

**Comment by isage** [comment]
And 3 should be fixed too.
So, the only problem left is misaligned background.

**Comment by Yukitty** [comment]
The background respects the Esc menu now, but not the map or item windows.

**Comment by isage** [comment]
That should be fixed now.

**Comment by Yukitty** [comment]
It still moves during the cutscene time freeze when you die.

**Comment by isage** [comment]
Oh god.
Fixed.

**Comment by isage** [comment]
Now background should be way better. I've also made motion walls wider.

**Comment by Yukitty** [comment]
I really like the way this turned out! :3 Good job!

The only thing I really feel is "missing" at this point is something to show you where the left and right boundries are in widescreen modes, since they're invisible... I keep trying to chase items into the abyss and getting stopped up.

And I have no idea what you'd even do for that, sadly. Some kinda laser wall like the Egg Corridor barrier?.. Some "strong current" tile animations..? The map is already hacked to disable tile rendering completely, so that'd just be even more of a pain... Guh.

**Comment by isage** [comment]
I think we should just try to expand boundaries on widescreen resolutions.
On "stock" resolution screen edges are boundaries, so that's kinda works fine.

**Comment by isage** [comment]
Welp, i''ve hacked the shit out of this map, by removing left/right blockers completely and blocking based on on-screen position. Also, turned out that on really wide resolutions there were holes in upper/lower walls (because it's not motion walls that block, its tiles), so i've turned whole upper/lower row into blockers.
That slightly affects how map looks on Map System, but eh
