### ISSUE TITLE
Missile launcher gets reordered to the end of weapon list

### ISSUE THREAD

**Issue by isage** [nxengine/nxengine-evo#53]
when collecting missile upgrade

**Comment by isage** [comment]
Hm, weapons are always sorted by their number.
@Yukitty can you recheck, please?

**Comment by Yukitty** [comment]
My mistake. u_u;; I wasn't paying enough attention. Sorry.
For some reason I thought weapons were sorted in the order you obtain them, but then obtaining the fireball puts them out of order and then it gets moved again when upgraded to super missiles, eesh.

**Comment by Yukitty** [comment]
Ah. Well at least I correctly recognised _something_ was wrong! \o/
Time to rename this issue to "weapon list order is just wrong", yeah?
Sounds like it'll be a bit of a pain to fix, since it's integral to how the game finds your weapons...
