### ISSUE TITLE
Chako's sleeping sprite needs to be re-added.

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#67]
Fixing Sue in the Sky Dragon's maw reverted Chako's sleeping sprite out of sprites.sif

Reopens #38 I guess.

**Comment by isage** [comment]
Fixed

**Comment by Yukitty** [comment]
I am noticing that her AI apparently uses the wrong sprite anyway now? It looks like you accidentally duplicated her entire sprite set and then only changed the last frame of the duplicate sprites, and only the left-facing frame while the right-facing frame became Mahin because of pressing autogen flip when there isn't actually a flipped version for this one.

**Comment by isage** [comment]
Yeah, i'm not that familiar with sifedit. 
Now both directional sprites should be the same.
(Although, i'm explicitly set direction in code, so that's strange)

**Comment by Yukitty** [comment]
![image](https://user-images.githubusercontent.com/8621403/42480823-f6eaeb16-83a4-11e8-893b-9ee002886629.png)
She's just standing up with her eyes closed.

**Comment by isage** [comment]
Goddammit. I hate sifedit.
Fixed. Again. For real, this time, i've checked.

**Comment by nlburgin** [comment]
How do you even _get_ sifedit? 

Does it have to built from source out of the "old" NxEngine codebase on Sourceforge? Is that the only place it exists? Is it basically the only way to edit sprites.sif?

Do you have to build against an unreasonably old version of WxWidgets for it to run correctly?

I've started an effort to adapt Nxengine-Evo to run Jenka's Nightmare, and while I've already got the extractor working for the credits illustrations and org files, it's clear that the game definitely won't run unless I do something about sprites.sif...

**Comment by isage** [comment]
I have a heavily modified copy based on a sourceforge version lying around,
didn't had time to properly clean it up and upload to github yet. Right now
it's incompatible with original one due to added support for per-direction
bounding boxes.
I'll probably get around to upload it on weekend.
(Initial idea was to drop it entirely and rewrite from scratch with Qt, but
alas)

**Comment by nlburgin** [comment]
So you're going to upload your version? 

Thank you, that sounds wonderful.

**Comment by isage** [comment]
@nlburgin https://github.com/nxengine/sifedit
Expect bugs.

**Comment by nlburgin** [comment]
Probably no worse bugs than I would have ended up with if I tried to build the original ;)

Thanks again.
