### ISSUE TITLE
Player MUST prioritize bonking over repelling.

### ISSUE THREAD

**Issue by Yukitty** [nxengine/nxengine-evo#70]
As noted in #26 and #69
The player has a lot of trouble fitting into 1 block high gaps, especially when moving left.

In the original game you would bonk your head against the ceiling before any sideways collision corrections are made, thus enabling the player to fit snugly into the gap. However, you would still be pushed sideways first while moving downwards.

The problem NXengine seems to have is that the player always vertically slides right past the gap as long as their momentum allows, the vertical collision not being detected regardless of which direction you're travelling. You are always pushed sideways out of the wall and thus never bonk your head on the gap ceiling.

**Comment by Yukitty** [comment]
Apparently the problem may actually be that the SIFSprite of the player needs wider/more "Block U" collision points..?? Why are collision testers part of sprites.sif? 🙀 Guh...

**Comment by isage** [comment]
Yes, and no. Making bigger block-u zone helps with horizontal gaps, but breaks vertical ones. This can be easily tested at the bottom of Mimiga Village.
>Why are collision testers part of sprites.sif
That's a question for rogueeve, however, original game just hardcodes them for player.

**Comment by isage** [comment]
Hm. However, making it exactly as in original game (10px wide) seems to work fine.
