### ISSUE TITLE
Add support rzx-50 platform

### ISSUE THREAD

**Issue by shikulja** [nxengine/nxengine-evo#72]
There is already an older project. But I want a single and fresh code.
https://exlmoto.ru/nxengine/
https://github.com/EXL/NXEngine/releases

**Comment by isage** [comment]
I don't have required hardware.
Pull requests are welcome.

**Comment by shikulja** [comment]
add link. github port 
https://github.com/EXL/NXEngine/releases

**Comment by isage** [comment]
Also, someone needs to port SDL2 to rzx-50 first (which, i'm pretty sure, won't happen)
