### ISSUE TITLE
HP-Tank pickup jingle repeats with New soundtrack

### ISSUE THREAD

**Issue by 16BitWonder** [nxengine/nxengine-evo#74]
As the title says, I've noticed that with the New/ogg soundtrack selected the
HP-Tank jingle repeats after having picked one up. (While the textbox is still open
and only says "Got a ^Life Capsule^!")
Pressing the confirmation key so it displays how much health you gained returns
the music to normal.

The other fanfaleX.ogg's seem to have this same issue when opening chests.

However, this does not seem to be the case with the Remastered/ogg11 soundtrack.

**Comment by isage** [comment]
Yeah. That also happens with gameover jingle.
Remastered soundtrack just has _loop.ogg files with silence, but "New" doesn't have that.
Original Org format tracks have loop-points (and jingles have looped silence at the end), but ogg format doesn't have that.
I wonder how they did that in CS+...

**Comment by isage** [comment]
Lol, they didn't. It loops in CS+ too.

**Comment by isage** [comment]
So, there are three ways to fix that:
1) modify original ogg files to add loop-points via vorbis comments. But, that requires additional step from users, and a way to read those comments (sdl_mixer doesn't have that ability)
2) just hardcode filenames of tracks that shouldn't loop. ewww.
3) add custom metadata files, that i can distribute along with binary. i think i'll go that way, but it'll take some time.

**Comment by isage** [comment]
I don't think we really need custom loop points ATM, although, it would be nice, for external OST (like dm dokuro) support, so i went third way, but instead of metadata just used empty flag-files.
