### ISSUE TITLE
Credit crash

### ISSUE THREAD

**Issue by Zemedic** [nxengine/nxengine-evo#81]
no error code just crashed

**Comment by isage** [comment]
Version? Platform?

**Comment by Zemedic** [comment]
> Version? Platform?
latest Windows 10 x64

**Comment by isage** [comment]
And by latest you mean latest release?
That was fixed long time ago, wait for next release or build it yourself.

**Comment by Zemedic** [comment]
> And by latest you mean latest release?
> That was fixed long time ago, wait for next release or build it yourself.

i cant build it do to and error if theres a better way tell me
