### ISSUE TITLE
Haiku port

### ISSUE THREAD

**Issue by win8linux** [nxengine/nxengine-evo#83]
Would it be possible to get a Haiku port working? I have been trying to make one for a few days now. At the moment, [this commit](https://github.com/win8linux/nxengine-evo/commit/66983b190f77f927c1e4ba452a2b972925dd061b) allows for the `cmake` step to proceed without issue. However, compiling it results in this:

```sh
~/nxengine-evo/build> make 
Scanning dependencies of target nx 
[  1%] Building CXX object CMakeFiles/nx.dir/src/ObjManager.cpp.o 
[  1%] Building CXX object CMakeFiles/nx.dir/src/ResourceManager.cpp.o 
/boot/home/nxengine-evo/src/ResourceManager.cpp:44:6: error: #error Platform not supported
     #error Platform not supported
      ^~~~~ 
CMakeFiles/nx.dir/build.make:86: recipe for target 'CMakeFiles/nx.dir/src/ResourceManager.cpp.o' failed 
make[2]: *** [CMakeFiles/nx.dir/src/ResourceManager.cpp.o] Error 1 
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nx.dir/all' failed 
make[1]: *** [CMakeFiles/nx.dir/all] Error 2 
Makefile:83: recipe for target 'all' failed 
make: *** [all] Error 2 
~/nxengine-evo/build> 
```

**Comment by EXL** [comment]
>this commit

You can bypass editing CMake FindModules in this way:

```bash
# For typical building
cmake \
    -DSDL2_INCLUDE_DIR=`finddir B_SYSTEM_HEADERS_DIRECTORY` \
    -DSDL2_MIXER_INCLUDE_DIR=`finddir B_SYSTEM_HEADERS_DIRECTORY`

# For Haiku OS recipe
cmake \
    -DSDL2_INCLUDE_DIR=/system/$relativeIncludeDir \
    -DSDL2_MIXER_INCLUDE_DIR=/system/$relativeIncludeDir
```
>#error Platform not supported

You can use this hack for a successful build app:

```bash
cmake \
    -DCMAKE_C_FLAGS="-D__unix__" \
    -DCMAKE_CXX_FLAGS="-D__unix__" \
```

**Comment by win8linux** [comment]
I've tried out your suggestions for CMake, however the compile still fails with this:
```sh
Scanning dependencies of target nx 
[  1%] Building CXX object CMakeFiles/nx.dir/src/ObjManager.cpp.o 
In file included from /boot/home/nxengine-evo/src/ObjManager.cpp:2:0: 
/boot/home/nxengine-evo/src/nx.h:5:10: fatal error: SDL.h: No such file or directory 
#include <SDL.h>
          ^~~~~~~ compilation terminated. 
CMakeFiles/nx.dir/build.make:62: recipe for target 'CMakeFiles/nx.dir/src/ObjManager.cpp.o' failed 
make[2]: *** [CMakeFiles/nx.dir/src/ObjManager.cpp.o] Error 1 CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nx.dir/all' failed 
make[1]: *** [CMakeFiles/nx.dir/all] Error 2 Makefile:83: recipe for target 'all' failed 
make: *** [all] Error 2 
```
It seems that it can't find a SDL header, which is weird for me since I've installed the necessary deps for building the code (`pkgman search sdl | grep "S       "`):
```sh
S       libsdl                                   A cross-platform media development library                                      
S       libsdl2                                 Simple Direct Media Layer 2.0                                                   
S       libsdl2_devel                      Simple Direct Media Layer 2.0 (development files)                               
S       sdl2_mixer                         SDL2 mixing library                                                             
S       sdl2_mixer_devel              SDL2 mixing library (development files)                                         
S       sdl2_ttf                               A TrueType font rendering library for SDL2                                      
S       sdl2_ttf_devel                    A TrueType font rendering library for SDL2 (development files)                  
S       sdl_ttf                                 Simple Direct Media Layer font library
```

**Comment by EXL** [comment]
@win8linux, try this.

```bash
> git clone https://github.com/nxengine/nxengine-evo
> cd nxengine-evo
> cmake \
    -DSDL2_INCLUDE_DIR=`finddir B_SYSTEM_HEADERS_DIRECTORY` \
    -DSDL_MIXER_INCLUDE_DIR=`finddir B_SYSTEM_HEADERS_DIRECTORY` \
    -DCMAKE_CXX_FLAGS="`sdl2-config --cflags` -D__unix__" .
> cmake --build .
```

**Comment by win8linux** [comment]
Yes, you're right; I did forget that step! I apologize for that mistake. Anyhow, I can confirm that it works under x86_64:

![image](https://user-images.githubusercontent.com/11584387/46464633-73e56e00-c7f9-11e8-8c91-bb462f3c9cce.png)

I will try it on x86 and x86_gcc2 before making a HaikuPorts recipe. Thanks for the help! :grin:

**Comment by EXL** [comment]
>before making a HaikuPorts recipe

Cool! But please use the original icon not from my package.
Identical icons in the repository is not very good.

**Comment by win8linux** [comment]
> use the original icon
Where is this? I don't see it anywhere in the repository.

Also, confirmed working on `x86`:
![image](https://user-images.githubusercontent.com/11584387/46469987-a6966300-c807-11e8-9a44-e752ec9739aa.png)

I got some errors trying to do the same thing on `x86_gcc2`, but I will try it on a clean system without the `x86` deps before posting them here.

**Comment by EXL** [comment]
>Where is this? I don't see it anywhere in the repository.

[It's here](https://github.com/win8linux/nxengine-evo/commit/d059e796a2159c7bd2842d909ec2c1213020af77#diff-1eb71284abf5cbcb712251e681beaf0aR17). You have to make your own icon with Icon-O-Matic.

>x86_gcc2

Drop this arch just `x86` is enough.

**Comment by win8linux** [comment]
> Drop this arch just `x86` is enough

Yeah, I will drop it now that the errors from the first comment are resurfacing when trying to compile on `x86_gcc2` even with the correct `cmake` arguments.

**Comment by isage** [comment]
@win8linux i took a look at commits in your fork.
Are you sure path-specific patches are required?
SDL has support for Haiku and should take care of settings location.

**Comment by EXL** [comment]
@win8linux: @isage is right!
The SDL2 library that nxengine-evo uses has a special function [SDL_GetPrefPath()](https://wiki.libsdl.org/SDL_GetPrefPath) for this. There is no such convenient feature in SDL1, so I had to add a specific Haiku OS paths.

You can also use something like this:
```c
const char *user_directory = getenv("XDG_CONFIG_HOME");
```
I recently checked this and it will work too.

**Comment by isage** [comment]
Well, latest master builds fine on Haiku and stores log/settings/savefiles in correct place.
