### ISSUE TITLE
Credit crash

### ISSUE THREAD

**Issue by B4rabbas** [nxengine/nxengine-evo#94]
Every credit, kazuma's end, doctor's end or even ballos 's one crash after few second.

**Comment by isage** [comment]
version?

**Comment by B4rabbas** [comment]
2.5.3

**Comment by isage** [comment]
See https://github.com/nxengine/nxengine-evo/issues/81

**Comment by B4rabbas** [comment]
Was not 2.5.3 but 2.6.3

**Comment by isage** [comment]
Still, see #81 
Wait for next release or build it yourself

**Comment by B4rabbas** [comment]
Ah ok, I was thinking it was last one, I'll build it when I'll have finish to correct the translation.

**Comment by B4rabbas** [comment]
Indeed this one is fixed
