### ISSUE TITLE
Final monster's damage cause invisibility

### ISSUE THREAD

**Issue by B4rabbas** [nxengine/nxengine-evo#99]
Take damage in the same taking time the last enemy's hp cause invisbility glitch, no hp neither ammo appairs in ui, until changing room
https://youtu.be/oFksJkkRRy8

Linux build 31/01/19

**Comment by B4rabbas** [comment]
In fact I've reproduced it, it's not especially for monster x but every boss, if quote take a damage when he shoot the last hp of any boss he disapeer

**Comment by kawa-yoiko** [comment]
Can reproduce, and I've made a fix at kawa-yoiko/nxengine-evo@3590889. Tested it with Igor for a few times.

What do you mean by 'demon'? If you can confirm that then let's make a PR.

**Comment by B4rabbas** [comment]
For "demon" I'm talking about the red gardians in the plantations where the mimigas work to grow red flowers for the doctor.

**Comment by B4rabbas** [comment]
I've just see it's name is droll.
Btw the issue is general to every ennemy

**Comment by kawa-yoiko** [comment]
I'm still not sure… I ran into a droll, took the damage and immediately gave it a fatal shot, but Quote just kept blinking after that.

Are these steps correct? Would you mind elaborating on how it's reproduced with normal enemies (not bosses), or provide a screencast?

**Comment by B4rabbas** [comment]
I've just touch the droll witheout attacking him.

**Comment by kawa-yoiko** [comment]
The character is visible after blinking if he directly runs into a droll.

Can you provide a screencast?
